-- Batch 5: 4 reviews. Run this whole file as one statement.
UPDATE "Review" AS r SET "contentEn" = v.body, "titleEn" = v.title
FROM (VALUES
  ('cmnn876uz0013cndevpenz9f5', $grulla$The special grade in Jujutsu Kaisen is reserved for the strongest of the strong, whether sorcerers or cursed spirits, and they are extremely rare and limited, giving us a sense of just how truly special they are. Sadly, among the curses, there are few in the special grade that are truly monstrous, with most of them being basically humanoids with particular traits. However, one of my favorite cursed spirits, and one that causes terror both inside and outside the world of Jujutsu Kaisen, is Kurourushi, our topic for today.

Kurourushi is a special grade cursed spirit released by Kenjaku's Cursed Spirit Manipulation during the Culling Game arc. What makes him particular is that Kurourushi participates in the games as just another player, and in fact he has some of the most interesting fights and abilities we have seen in the arc.

Kurourushi looks like what you would expect from a cockroach cursed spirit. His face, arms, and legs have the appearance of being made from a light-colored insect exoskeleton. Kurourushi is quite tall and can produce up to four human arms. He also possesses human hands and feet, and his abdomen is completely hidden by a black cloak that extends down from his head. He generally covers his wings and extremities, but they can be seen when they move.

Kurourushi's face is grotesque and perfectly reflects the alien nature of an insect like a cockroach. With six long antennae protruding from it, Kurourushi's face has eight separate sets of eyes in different places and human-like teeth behind his multi-layered jaw.

Kurourushi does not possess a distinctive ego and is instead driven entirely by his instincts as a cursed spirit. He only wants to devour humans in an attempt to satisfy his insatiable appetite. He feels disgust toward anything that gets in the way of his feeding.

When Yuta interrupted Kurourushi's meal after he awoke in a state of hunger, the cockroach curse focused solely on devouring him instead. Kurourushi even questioned why Yuta was interfering. When Yuta responded by asking why Kurourushi kills, the cockroach curse simply stated that he loved the taste of iron.

Kurourushi is one of only sixteen registered special grade cursed spirits. Humanity shares a collective fear and disdain for cockroaches, which gave rise to Kurourushi. He possesses the unique physiology of a humanoid cockroach, as well as the ability to summon and manipulate endless cockroaches reinforced by his cursed energy. In addition, Kurourushi can use cursed techniques and wield his signature cursed tool, the Putrid Life Sword, an especially dangerous weapon. At some point in the past, Kurourushi was defeated by Suguru Geto or Kenjaku and was absorbed into Cursed Spirit Manipulation. Kenjaku released Kurourushi so that the cursed spirit could compete at an elite level in the Culling Game.

Despite generally acting on the instinct to satisfy an endless appetite, Kurourushi is a relatively intelligent creature compared to most cursed spirits. Although not to the degree of the unregistered special grades like Jogo, Mahito, Hanami, or Dagon, Kurourushi can speak and communicate clearly. He understands his own status within the Culling Game and collected fifty-two points before reaching a stalemate with the most powerful players in the Sendai colony. The cockroach curse was intelligent enough to understand that Dhruv would have been an unfavorable matchup and decided to enter a state of hibernation. Kurourushi also prepared for the worst by creating offspring that would inherit his cursed energy in case he was exorcised.

In terms of power level, Kurourushi was born from the collective hatred, fear, and resentment associated with cockroaches. These negative emotions manifested special grade levels of cursed energy. Each cockroach under Kurourushi's control is imbued with his cursed energy and possesses enough strength to devour a human being as a group. Kurourushi consistently manipulates large quantities of cockroaches while also using cursed techniques, demonstrating meticulous and innate control.

Kurourushi can produce and control countless swarms of real cockroaches reinforced by his cursed energy. These man-eating cockroaches can strip all the flesh from a group of humans in a matter of seconds. This feeds Kurourushi's endless appetite and stimulates parthenogenesis. A single cockroach poses no real threat, but a full swarm can be a serious problem even for a jujutsu sorcerer.

The flesh devoured by the cursed cockroaches stimulates Kurourushi's process of parthenogenesis, granting him the ability to produce more cockroaches. In addition, Kurourushi uses this to reproduce an identical but completely new cursed spirit offspring. To preserve Kurourushi's existence, the parent's cursed energy is passed on to the child when it dies. In a way, this makes the concept of Kurourushi, rather than the creature itself, relatively immortal, as long as he has enough time to create his offspring before being exorcised.

One particular ability he shows us is his Earth Insect Trance, a cursed technique that conjures flying insect curses carrying large sacs filled with a liquid substance that is released when they are destroyed. The substance enters the target's eyes to affect their vision, giving Kurourushi time to escape, or to attack his opponent from another angle.

Of course, Kurourushi also has his iconic cursed tool.
The Putrid Life Sword is said to be an enchanted blade that mixes life and death. It is a short, thick sword, similar to a butcher's knife, with a unique shape and a grotesque design fitting for an insect to wield. Its most prominent features are six distinct firing barrels on the front of the blade that can launch short-range projectiles at its target.

Even if the sword is blocked by the opponent's weapon, it is able to fire small eggs into the enemy's flesh to infect them. Shortly after embedding themselves in the target's skin, the eggs hatch and small insect-like curses emerge from the wound. The same effect occurs if the blade cuts the target directly as well. This is what gives Kurourushi an advantage against opponents who focus on mid-range attacks like Takako Uro, whose arm he ended up cutting off with this weapon before being exorcised himself.

Kurourushi is not really one of the cursed spirits with the greatest presence in the Culling Game arc or in the Jujutsu Kaisen series, but his abilities and especially his presence as a balance to the characters of the Sendai colony are very important to the story, and he warrants discussion, despite being simply a giant cockroach with a butcher's knife.

We cannot forget that the fact that special grade curses exist who can put up a fight not only against Uro and Ryu but against Yuta himself shows us the power level of the 16 registered special grade curses, so the existence and use of Kurourushi in the story is quite relevant, and despite not being the strongest in the world, his concept and theme are very interesting for lovers of horror and character design in Jujutsu Kaisen.

Now, on the darkest night, be careful with the corners covered in shadows, because there may be a hungry creature straight out of your nightmares hiding right there.$grulla$, $grulla$Kurourushi$grulla$),
  ('cmnn876m50011cndeqs5j9o35', $grulla$There are character clichés in the world of anime that everyone knows, and one of the most prominent and beloved by many is the hooligan with a heart of gold. Those characters who look aggressive and know how to fight, yet who don't hesitate for a single second to protect the weakest people or to save someone in danger. Even in a fantastical shonen like Hunter x Hunter, we have this kind of character, but with twists that are even more unexpected, which make our character for today, Knuckle Bine, feel fresh and different, and manage to capture the attention of many of us.

True to his character archetype, despite seeming aggressive, Knuckle is very compassionate and is easily moved to tears. He gets along well with animals and feels obligated to protect the defenseless, taking care of the pets abandoned after a genocide. However, Knuckle's empathy sometimes interferes with his mission, making him a talented but troublesome member of the beast hunters, and a mismatched pair with Shoot on their mission during the Chimera Ant arc.

In the past, when Knuckle graduated from elementary school, he punched a police officer to help his friend escape, fleeing from a patrol of cars and motorcycles for a day and a night without being captured. At one point, Knuckle felt motivated to pass the Hunter exam in order to try to protect all the animals he could, and he became the apprentice of Morel, an extremely renowned hunter. An interesting fact is that even though Knuckle is a relatively new hunter, his love for protecting others has led him to wage more than 5,000 battles, an extremely high number for his age.

Despite seeming impulsive and foolish, Knuckle is one of the most strategically patient and intelligent characters in the entire series, demonstrating composure in difficult moments as well as the ability to use his powerful but hard-to-apply technique in extremely creative and effective ways.

In terms of power level, Knuckle has demonstrated considerable abilities in physical combat, being capable of fighting enemies much stronger than himself. He could have defeated Gon with just two punches if not for his kindness, which has often been said to be his greatest weakness. In fact, Killua stated that he is as strong as Kite, physically speaking, but is too soft. Because of his ability, he has adopted a hit-and-run tactic together with Shoot against other Nen users, which consists of capturing or delivering the final blow after the target's Nen is sealed. Knuckle is very versatile, being able to successfully cooperate with various Hunters who have completely different abilities and personalities. Despite being a good strategist, Knuckle is also impulsive and very emotional, which can cause him not to stick to the plan.

A curious aspect is that he is slow to start taking fights seriously, claiming he needs four or five punches to warm up.

In addition, he is very loved by animals, which, according to Ging and his son, is proof of being a good Hunter.

An interesting point is that physically Knuckle is stronger than an Enhancer like Gon, without being an Enhancer himself. He is capable of making him feel as if he were burning after one of his punches.

It is also known that Knuckle is faster than Gon. He demonstrated this by surpassing him in movement speed to the point of being able to appear behind him after landing a punch. Even after repeated battles, and despite matching him in attack speed, Gon considered his eyesight unreliable for following Knuckle and instead relied on his aura. Knuckle managed to dodge multiple attacks from Youpi while fleeing despite the latter's reach, as well as to escape his explosions twice despite being very close to the epicenter just before the detonation. He got used to Cheetu's astonishing speed and was already able to follow him with his eyes after the first exchanges, although his body was too slow to keep up with his reflexes.

Notably, Knuckle is not only fast, but also has very good stamina, being able to maintain his speed for a long time. All of this together makes Knuckle an extremely strong hunter even without using his Hatsu, perhaps even one of the most powerful we have seen, excluding of course the most extreme cases such as Hisoka, Chrollo, or Netero.

As far as his Nen is concerned, being a professional hunter and the disciple of a Single-Star Hunter, Knuckle is a highly trained Nen user. Since he managed to surpass Gon and Killua and inflict significant damage on the former despite his natural category, he also seems to be well versed in enhancement, despite it not being his main category. His abilities in this type helped him survive Gon's full-power attack without lasting injuries despite his lower aura output. Of course, Knuckle's main Nen category is conjuration, given his ability to conjure a Nen beast. He is a capable user of Ko, Ryu, Gyo, and Zetsu. In battle, he can maintain a state of Ken for 20 minutes without the slightest difficulty. He is skilled at anticipating his opponents' movements by analyzing the flow of their aura. He also excels at converting aura into numbers, which is extremely useful for his Nen ability. Thanks to his vast combat experience, he can estimate the general amount of aura an opponent possesses through physical contact, or make more precise guesses through prolonged observation, taking into account their output, stamina, and skill level.

His Hatsu is called Hakoware or Bankruptcy, and it is, in my opinion, the most interesting but complex Hatsu of all the ones we have seen.

Hakoware involves Knuckle conjuring an indestructible Nen Beast called the "Amortization Power Redirector or (A.P.R.)" onto the opponent after they have received a punch from Knuckle, emitting his aura into his opponent. A.P.R. constantly lends Knuckle's aura to whoever it is attached to, which is shown by a rising counter on their forehead. When adding interest, A.P.R. announces "It's time to add interest." As long as A.P.R. is attached, any attack made on Knuckle by his opponent returns aura to him, reducing the counter. Until all the aura lent by Knuckle is returned to him, his opponent cannot physically harm him. The reverse is also true: each of Knuckle's punches only lends more aura to his opponent, without causing damage. The stronger the attack, the more aura is lent or returned. In both cases, the person who receives the blow can still be knocked down by it, despite not suffering any damage.

A.P.R.'s interest rate is 10% of the lent aura, which accumulates every 10 seconds as long as the victim is within 50 meters of Knuckle. As the amount of lent aura (including interest) accumulates, A.P.R. also grows in size. When the aura lent by Knuckle exceeds the opponent's total remaining aura, the opponent "goes bankrupt." Therefore, it is in Knuckle's interest for his opponent to spend/waste as much aura as possible, as fast as possible (as long as that aura is not spent on Knuckle himself). The result is that the opponent's "aura balance" drops much faster until it is below the amount they owe Knuckle (shown by A.P.R.), at which point they can no longer pay their debt, and bankruptcy is established.

Bankruptcy causes A.P.R. to transform into the "Individual Ren Suppressor or (I.R.S.)," a demonic pet that follows the debtor for 30 days and forces them to be in a continuous state of Zetsu. It is worth mentioning that when Knuckle hit Shaiapouf's copy, A.P.R. attached itself to the latter's real body instead of his clone, making it useful against this type of opponent. Furthermore, Knuckle can use Hakoware on multiple targets at once, as well as track their general location at all times, regardless of distance. The ability can be removed by an Exorcist, but it heavily drains the one removing the Nen. It is also canceled if Knuckle is knocked unconscious.

Although the Nen types used by Hakoware are confusing, it is clear that it at least uses conjuration to call the Nen beast, and it is possible that it uses emission to lend his aura to the opponent. It is considered an extremely advanced and precise technique, since it not only requires Knuckle to be able to convert aura into nominal values, but the ability to inflict a state of Zetsu and prevent the user from using their Nen is extremely rare, valuable, and difficult to control.

Knuckle's personality and ability make him one of my favorite characters in all of Hunter x Hunter, and although he is confusing to understand at times, we have seen how he has been able to stay in the fight using his intellect and physical abilities in addition to his Hatsu, even against some of the most powerful opponents we have seen in the series, such as Youpi and Pouf. In addition, the understanding of Nen that Knuckle gives us is easy to undervalue, since thanks to him, its incredible magic system is understood more deeply.$grulla$, $grulla$Knuckle$grulla$),
  ('cmnn876d9000zcndeo7n245tl', $grulla$Master figures are essential to most Shonen. These characters are crucial for characterizing the protagonists, and through them a great deal of exposition is delivered about how the world of these series works. However, the potential of these characters to motivate or change the protagonists is rarely used to the fullest, given the close ties between them and their masters, and when this is executed perfectly, as Hunter x Hunter does with Kite and Gon, it becomes something unforgettable, and one of the most important pivot points we have seen in the world of Shonen. In this video, we will explore the character and Nen abilities of Kite, Gon's master figure, and try to understand why his death had the impact it did on our protagonist.

Kite is severe and stoic, occasionally blunt to the point of seeming rude. Although some may consider him cold, he is actually caring; he likes animals just as much as people. However, he never hesitates, not even when he must take a life, even if he dislikes it: in fact, after saving Gon, he struck him because his ignorance led to the death of a Foxbear.

It is clear how Kite has an extremely pronounced paternal side, and we could even say he is Gon's real father figure in addition to being his master, which explains the attachment the boy has to him. Ging's abandonment of Gon, and the time Gon spent in his childhood with Kite, marked him deeply, shaping his personality, which demonstrates Kite's ability to influence others.

What is interesting is that even after his death at the hands of Pitou, and the consequences this had for Gon, we see another side of Kite following his reincarnation as a Chimera Ant. During her initial introduction as the Queen's last offspring, Kite is presented as an enthusiastic little girl, still playing with stuffed toys and swords, and still being cared for by Colt. However, after only a few days, she matured and seemed to return to her former personality as a result of recovering her memories. She then helped both Koala and Gon to ease their feelings of guilt and gave the former a new purpose in life, although she framed it as a threat. This demonstrates not only her compassion and influence once again, but also her analytical skill and tactical intelligence.

In terms of power level, Kite is one of the strongest Hunters we know of, with extremely interesting abilities. He is not only an expert swordsman, as demonstrated by his skill with his Tachi, or elongated Katana, but he is also capable of fighting with a varied range of weapons, as demonstrated by his hatsu, which we will discuss shortly.

Kite, like Gon, is greatly appreciated by animals, a trait that, according to Ging, identifies a good Hunter. In the few years after passing the exam, he discovered 68 new species. One of his most impressive achievements, however, remains tracking down his master, the elusive Ging Freecss. His competence allowed him to mentor a group of amateur Hunters, as well as to guide novice Hunters like Gon and Killua. While they were in NGL, Killua observed that he and Gon together were weaker than a one-armed Kite. Kite could effortlessly defeat high-ranking Chimera Ants, organisms he had never encountered before, and even managed to inflict some superficial wounds on the newborn Neferpitou with only one arm, though at the cost of his life. When he was revived as a corpse, Shoot and Knuckle had to cooperate to defeat him and considered him a difficult adversary.

As for his Nen, Kite is a Conjurer with a dual affinity toward Transmutation. Given that he was trained in Nen by Ging, one of the best Nen users in the world, it can be assumed that Kite is highly proficient in this field. He is known to have a powerful aura. His En has a radius of about 45 meters, with fluctuations of 2 or 3 meters depending on his physical and mental condition, and he appears to be capable of masking it with In, since Gon and Killua were unable to notice that he was using the technique.

Kite's Hatsu is called Crazy Slots.

Kite can conjure a variety of weapons with a clown-shaped Nen beast attached to them. A slot machine appears on the clown's tongue with numbers from 1 to 9, each corresponding to a specific weapon. Whatever number appears randomly, the weapon corresponding to that number is conjured, which means that Kite cannot choose which weapon to summon. He included this restriction in order to increase the power of the individual weapons. The summoned weapon will not disappear until it has been used. The clown can also speak and comment on Kite's actions and conditions, usually to his annoyance. Only three of his weapons are shown in the manga: a scythe, a rifle, and a mace. Additionally, according to Ging, the Crazy Slots ability has a number that only appears when Kite desperately does not want to die. This ability is interesting because it demonstrates that his power is so great that Kite managed to reincarnate as the Queen's daughter after his death.

Let's talk about the known numbers:

Number 2: Silent Waltz

Kite conjures a very sharp and enormous scythe. It cannot be dismissed until Kite uses it against his opponent.

After increasing the size of the blade, Kite swings it in a circle, generating an invisible cut that spreads in all directions. When he used it against the Chimera Ants, he split them all in half and knocked down the trees around them.

The scythe is not one of Kite's preferred weapons, and he considers it a poor choice overall, which is strange considering his skill with the sword. However, even though it is a weapon he dislikes, he turns out to be extremely skilled and lethal with it.

Number 3: Mace

Kite conjures a mace or a staff with a clown's appearance, which he seems to wield with a reverse grip. The true orientation and function of this weapon are still largely unknown. However, the clown refers to it as a "good number," probably referring to its simplicity of use and attack power.

Number 4: Rifle

Kite conjures a firearm with a shape similar to a long-barreled pistol combined with an extremely long stock. It can fire powerful bullets in rapid succession and apparently without making any noise. The long front element of the weapon appears to be some kind of silencer, which explains the lack of noise when firing. This is one of Kite's few ranged weapons, and he appears to be just as skilled with it as with his close-range weapons.

We cannot forget the conditions for using his abilities: he cannot choose the weapon he is given, and the one that is summoned must be used before it can disappear. We can assume that these are his own conditions for strengthening the summoned weapons, in the same way that Kurapika did to strengthen his chains.

Sadly, we never learned the other numbers of Crazy Slots, so we do not know the full extent of Kite's hatsu or of his power level. Tell me in the comments which weapons you think would be associated with the other numbers.

It is confirmed that Kite lost his Nen abilities after his rebirth. However, it is not confirmed whether this changed his Aura type, whether his abilities can be relearned, or whether he is even capable of using Nen at all in his new body.$grulla$, $grulla$Kite$grulla$),
  ('cmnn87641000xcndekpkhz447', $grulla$Every series worth its salt has those characters who are not merely supporting players helping to round out the protagonist, but who in many moments feel like protagonists themselves, being an essential part of the story and evolving just as much as, or even more than, their protagonist counterparts. These kinds of characters tend to be my favorites, and Hunter x Hunter gives us the best example of this with our little assassin from the Zoldyck family, Killua.

The key theme throughout Killua's entire character arc is the psychological concept of nature vs nurture. Nature vs nurture is a simple idea, but it has been an important topic of conversation in society ever since the question first arose. Nature has to do with genetics. It poses the question: are all humans and their behaviors a product of their DNA? Nurture has to do with the environment a person has had to live in. The nurture side asks: are all humans a byproduct of their surroundings and of the people they grew up with? Ultimately, the theory seeks to answer the question of how much control people have over their lives.

In Killua's case, understanding this concept is key, since it is the essence that drives his story. Killua is the heir of the Zoldyck family, a family of elite assassins who have been training him to be the head of the family since his birth. From the moment he drew his first breath, Killua has been subjected to torture, sent on missions to assassinate people, and forced to play psychological games with every member of his family. Being the head of the family is the only reason for his existence in the eyes of his family.

At the same time, Killua is also just a kid trying to find his own way in life. He was born with a good heart and is a fiercely loyal friend to Gon and to anyone else he considers a friend. Time and again, he proves to be a compassionate person who wants the best for those he cares about. Despite his own struggles, he has the endless motivation to be more than what others say he is.

The friendship between Gon and Killua is of the utmost importance to the development of both characters. Their mutual influence is tangible, especially as the show moves toward its final arcs. When the pair first meet during the Hunter Exam arc and up through the Zoldyck Family mini-arc, Killua simply wants to be Gon's friend. This is where the first great moment of his nature pushing back against his environment occurs. Killua hears that his friends have come for him while he is being tortured, and he frees himself with ease. He packs his things and heads to his father's room to tell him he is leaving. Surprisingly, he receives his father's blessing, and with that, he takes an important step on his path of personal growth.

The seed of his greatest internal conflict, that of his self-esteem, was planted in his childhood and slowly began to manifest during his time with Gon in the Yorknew City and the Greed Island isekai arcs. For example, at the end of the Greed Island arc, when Gon thanks him for always being there for him, Killua gets shy and turns away, thinking to himself that the roles should be reversed. Even though he has put a great deal of effort into the friendship, he still sees himself as being indebted to Gon.

In terms of power level and combat, Killua has been trained since birth to become a human weapon and is recognized by his family as the most talented assassin in the entire history of the Zoldycks. When he took the Hunter Exam for the first time, he was the fourth most powerful applicant (after Gittarackur, and, by his own admission, Hisoka and Hanzo). Up until the Hunter Exam, he wouldn't hesitate for a second to kill, but after meeting Gon this tendency diminished; even so, he is not afraid to resort to extreme means when circumstances demand it. Like his friend Gon, Killua has an astonishing natural talent that allows him to learn at a rapid pace and, supposedly, ad infinitum, a trait that sparked Hisoka's interest. His potential extends to Nen as well, as pointed out by Wing and Bisky. Although he fights mainly with his bare hands, Killua can use any kind of weapon, but the only one he consistently employs are his custom-made yo-yos. When he tried to prevent the Selection, he was so confident in his strength that he claimed tanks and fighter jets would be useless against him, and indeed, he was able to effortlessly subdue a military unit made up of at least four tanks.

His training granted him near immunity to poison, a high tolerance for electricity, great agility and physical strength, advanced armed and unarmed combat techniques, and stealth techniques, all of which he acquired at a very young age. He can also drive vehicles of any kind, including aircraft. His exceptional intellect and analytical skills are equally remarkable, and it is often through strategy that he can defeat opponents who are stronger or more experienced than he is. He is also capable of walking without making a sound and sleeping with a larger portion of his brain awake than normal, so that he can avoid attacks even while asleep, even if they come from a fellow armed, though weaker, Hunter. After leaving Greed Island, due to his prowess in Nen, Killua became able to blend in with nature more easily.

Killua's main weakness used to be an inferiority complex that paralyzed him with fear and prevented him from fighting opponents who could pose a threat to him, even if their overall strength was less than his own. Although it was originally believed to be a product of his training, it is later revealed that it was actually due to a Nen-imbued needle that Illumi had implanted in his brain. Its removal freed Killua from his brother's conditioning, thus regaining full control of his mental faculties in battle. This also had the effect of improving his overall movements, increasing his speed.

When it comes to his Nen abilities, Killua is a Transmuter with a dual affinity toward Enhancement. Killua is most efficient at changing the properties and shape of his aura. Like Gon, Killua's talent is said to be absolutely astonishing, found in only one out of every ten million people. Thanks to Bisky's training, he has refined his skills in at least two types of Nen besides his own, namely Enhancement and Conjuration. He has also mastered the four basic techniques and at least five of the advanced ones (the exceptions possibly being In and En, though he can extend his Ren to a radius of 57 cm to detect incoming attacks). He performed Ten successfully on the first try with almost no instruction, and learned Ren and Gyo in just one night. He was also able to perform Zetsu with great skill and without guidance after watching Gon use it against Gido, earning him praise from the Phantom Troupe, though they were able to detect him. He can maintain Ren for three hours outside of combat without the slightest difficulty, and Ten at all times. He can form Ko in an instant, as demonstrated when he used it to knock out Gon while the latter was going to fight Neferpitou. Although Gon can release a greater amount of aura, Killua is generally hailed as the one with the better control, to the point that when he faced Razor he was already able to distribute his aura with a margin of error of less than 1%, which led Bisky to comment that she only reached his degree of mastery in her twenties. Despite his lack of experience, he can accurately gauge how much aura to employ and in which area in a fraction of a second, relying solely on the instinctive knowledge granted by his fearsome potential. He easily surpassed Gon during their training on Greed Island, overcoming his inexperience with pure intuition.

Killua developed a series of Nen abilities in which he alters the properties of his aura to make it similar to electricity. This was inspired and made possible by the years of electric shocks he received as a child, both as training against torture and as punishment. Bisky was very impressed that he could create such a complex Nen ability at his age. He can electrocute his opponent either through physical contact or while keeping his distance, channeling his aura through his yo-yos or launching it in the form of a bolt. Although most Nen users take no damage from the electricity itself, they are still wounded and paralyzed for a few moments.

Killua has a series of special techniques that he employs through his electricity. These are:

Lightning Palm:

This is the most basic of Killua's Nen abilities, with which he uses his palms to electrocute his opponent with a shove. This paralyzes the opponent for a few seconds, allowing Killua or his allies to attack or escape.

Thunderbolt:

With this technique Killua jumps into the air and fires a bolt from his fingers, paralyzing the opponent and causing a good amount of damage. Although its power was not able to finish off even Rammot, we saw how it was strong enough to incapacitate Youpi for a few moments.

Godspeed

The first main function of this technique allows Killua to react automatically to external stimuli. Instead of the normal process in which the stimulus is perceived by the nerves, which transmit a signal to the brain, which in turn sends an instruction to the muscles, Killua programs his aura to send an electrical signal to his muscles to react instantly to a threat, thus bypassing the nervous system, which is comparatively slower. The aura can be preprogrammed to respond to different stimuli: physical contact, malevolent intent in the enemy's aura, or someone stepping into a predetermined perimeter, and the specific response is also preprogrammed.

Specifically, this results in a drastic increase in Killua's reaction time, which has both offensive and defensive uses. When Killua used a prototype of this ability, he was able to grab a dart the instant it was conjured, already in contact with his skin, and the moment it pierced him. The Whirlwind, as part of this ability is called, is also effective as an offensive ability. If the opponent executes the action for which Killua has preprogrammed a response, in most cases he will be able to attack before the opponent does, thanks to the fact that both his reaction time and his movement speed are drastically improved. When he used this application of Godspeed against Youpi, Killua was able to momentarily disappear from his sight and strike him several times without him being able to do anything, the brief lapse between the increase of the Royal Guard's aura and his action being enough for Killua to anticipate any move from his adversary. Youpi himself admitted to feeling completely helpless during the beating. On that occasion, even though his attacks inflicted no damage, Killua's electricity was powerful enough to provoke cries of pain from Youpi, as well as to paralyze him for a few moments. When he later used the same ability against Shaiapouf's clone, which is considerably fast itself, Killua was able to dodge its attacks with Komugi on his back, which led Pouf to fear that even with all of his cells, he would have difficulty catching him, and then he burned his cells by generating an electric current between his fingers each time the clone stepped on a circle he had drawn.

Since giving an order to one's aura is generally a Manipulation ability, it is possible, though unconfirmed, that Killua's Whirlwind uses this category of Nen.

The second application of Godspeed allows Killua to maintain conscious control of his movements. His running speed and jumping ability increase drastically, so he uses it mainly to cover long distances in very little time. As a consequence, this main function is more affected than the Whirlwind by the terrain: Tsubone could keep Killua in sight while he ran through the forest, but lost sight of him as soon as he reached a paved road. However, even at full speed, he was significantly outpaced by Tsubone's motorcycle transformation while she carried two passengers. The butler estimated that crossing the forest would take Killua about 10 minutes to reach a destination some 40 km away, while a car driver would take twice as long. This suggests that on unfavorable terrain, Killua's speed with his Godspeed is approximately 240 km/h.

As you can see, Killua's ability, although it appears to be quite simple, is supremely complex when we analyze how it works in its application of Nen, which perfectly reflects his development as a character. Personally, it is one of my favorite abilities, both for its use in battle and for how it reflects Killua's past and his way of fighting as an assassin.$grulla$, $grulla$Killua$grulla$)
) AS v(id, body, title)
WHERE r.id = v.id;
