-- Batch 4: 4 reviews. Run this whole file as one statement.
UPDATE "Review" AS r SET "contentEn" = v.body, "titleEn" = v.title
FROM (VALUES
  ('cmnn877v6001bcnde9ka4yn00', $grulla$---
aliases:
 - Mai / Yorozu
---

Cursed techniques in Jujutsu Kaisen have always been an expression of their author's imagination, a way of giving different and creative powers to his characters, but some techniques are more creative than others, and none represents this concept more than the innate cursed technique of not one but two characters in the series, Mai and Yorozu, who share the difficult-to-use technique of Construction.

Construction, as its name implies, allows the user to conjure an object out of nothing. Unlike objects created inside a domain, anything constructed will remain even after the technique is finished. However, this uses a large amount of cursed energy inefficiently, which can cause a strong adverse reaction in the user's body.

Mai

Mai is Mai's twin, whom we meet briefly during the competition between the Jujutsu schools of Tokyo and Kyoto,

Like her twin sister, Mai was mistreated by the Zenin clan while growing up, simply for being a girl with little talent for jujutsu. Mai was content to live under their control as a servant and preferred doing household chores rather than fighting. Maki, on the other hand, preferred to defy the clan and work as a sorcerer. The repercussions of Maki's rebellion forced Mai to study to become a jujutsu sorcerer. Because of this, Mai detests the grotesque work of exorcising curses and resents Maki for essentially throwing them both into that life.

Mai developed the Construction technique and hid it from her twin sister while they were growing up. She uses a revolver in battle, so after firing six shots at Maki, it seemed she had run out of bullets. However, Construction allowed her to create and load another bullet charged with cursed energy into her revolver. This surprise attack was meant to catch her opponent off guard and end the fight.

Mai's limit is one bullet per day, but this drained the little cursed energy she possessed, resulting in physical consequences such as a nosebleed. After being cut down by her own father, Mai decided to use Construction to give her sister Maki a fighting chance. Mai was aware that the repercussions would kill her, but she seized that opportunity to take all the cursed energy between the twins. Mai sacrificed her life to give Maki a body of steel that escaped cursed energy, using Construction to create a great sword that symbolizes the bond between the two.

Sadly, Mai is more of a vehicle to empower Maki and doesn't have great feats or much to mention when it comes to Construction. For that, we have to talk about the other exponent of the technique.

Yorozu

Yorozu is one of the sorcerers reincarnated during Kenjaku's Culling Game, who took over the body of Tsumiki Fushiguro in her new life. In the Heian era, Yorozu was considered an extremely talented sorcerer, even recognized by the powerful Fujiwara clan. Her obsession with Sukuna is everything to her, and it's clear she would do anything to be with him, even going so far as to propose defeating him in battle if he promises to marry her.

As with Mai, Yorozu's innate technique allows her to create any matter using her cursed energy, as long as she has some knowledge and information about the matter she wishes to create. This lets her make creations that combine the properties of several different elements and materials.

Unfortunately, the cursed energy efficiency of her technique is severely lacking, even though her own cursed energy output is on par with the strongest fighters of the Heian period. This obviously causes great frustration in Yorozu, who dedicated her life to tirelessly researching a way to solve this problem.

Eventually, Yorozu slowly began to glimpse a solution to her technique's weakness. Realizing the energy efficiency of an insect's body, Yorozu came to believe that creating armor incorporating the physical aspects of various insects would largely solve Construction's energy inefficiency. This allows her to fight on the same level as, and even surpass, some of the most powerful jujutsu sorcerers of the Heian period, earning the recognition of the Fujiwara clan.

Using Construction, Yorozu can create more than mere bullets like Mai. One example of this is her insect wings, which allow her to fly at high speeds, or her liquid metal, which she uses as her main combat tool. This liquid metal can change its volume at will, and its stable physical characteristics allow it to take whatever form Yorozu requires for combat by manipulating it with cursed energy.

Yorozu can also create insect armor with the liquid metal. This is the solution to the inefficiency I mentioned earlier; Yorozu considers an insect's shell to be the ultimate armor and the ideal subject for Construction. This greatly enhances her strength, speed, and endurance, improving all her close-quarters combat abilities. It also allows her to increase her skill in mid-range combat by continuing to control liquid metal outside the armor, attacking from multiple fronts.

All of this shows us that Yorozu's control over Construction is exceptionally proficient. Her greatest achievement was even being able to create a perfect sphere, a feat considered impossible. A true sphere has no contact area and generates infinite pressure as a result, making it untouchable. It moves toward Yorozu's target at a moderate speed and becomes an obstacle in combat that her opponent must avoid at all costs or be destroyed, giving them an additional complication in fighting her.

Of course, we can't overlook that Yorozu's techniques don't stop at her mere innate technique; she is skilled enough to have her own domain expansion.

Domain Expansion: Triple Affliction

The setting of this Domain Expansion takes the form of an empty space with several oversized organic structures floating in it, resembling the disembodied brains and ventral nerve cords of insects. The domain's sure-hit effect applies to the objects constructed by the user, and by applying this effect to her true sphere, Yorozu can basically destroy the opponent instantly if they are caught in her domain.

What's interesting about Construction in the context of Jujutsu Kaisen is that, despite seeming like an extremely powerful technique, it's much more difficult to use than it appears, and it requires creativity, effort, and additional study to be as effective as the techniques of the other characters. Both Mai and Yorozu showed us different levels of Construction, and I'm grateful to both of them for giving us one of the best interpretations of this type of technique in any anime or manga series.

Tell me in the comments, what other cursed technique would you like to see explained? I'd love to hear your opinion. Also, if you liked this video and want to see others like it, don't hesitate to subscribe, and give the video a like; it helps me grow the channel a lot.

Take a look at this perfect sphere, it's the culmination of all my effort. Hey, but what do I know, I'm just a crane that comments.$grulla$, $grulla$Mai & Yorozu$grulla$),
  ('cmnn877m70019cndevlkoqsf4', $grulla$No one would blame you if, when you watch Hunter x Hunter, you focus on the strongest and most complex characters in the series, if Gon, or Killua, or Kurapika, or even Hisoka or Chrollo are your favorites. However, there is another character in the main cast who, although he is the one with the least screen time, has profound effects on the personalities of his companions and on the story itself whenever he finally deigns to appear, and whether you like his personality or not, he is in my opinion the best example of an effective support character in this story. Of course, I am talking about our favorite greedy doctor, Leorio Paradinight.

Leorio is initially presented as a very self-centered narcissist who places great emphasis on material wealth. However, despite his claims that he is only after money, he eventually reveals to Kurapika that his dream is to become a doctor in order to help the poor. He believes that all things in the world (lives, dreams, etc.) can be bought and that becoming a Hunter will provide him with the funds necessary for his medical education. Due to his first confrontation with Kurapika, as well as the test on the way to the navigator's cabin, it seems that he is sensitive toward those who do not take him seriously or treat him with disrespect. His true priorities seem to be his friends first, then his dream of becoming a great doctor, and after that everything else.

Leorio is not someone who backs down when faced with overwhelming odds in a battle. He is a loyal and reliable ally who greatly values the bonds of friendship, and he acts as the 'big brother' of the group. He often provides the comic relief in the story; Killua sometimes teases him about his comparatively older age, even though he swears his appearance is that of a mere teenager. His impulsive and bold nature has sometimes caused more problems for the people around him. Another ability he has is his capacity to "speak plainly" in many situations. You could say that his closest relationship in the group is with Kurapika, since they have spent most of the time together.

An interesting detail is that, at the end of the Yorknew City arc, Melody states that he has "the kindest heartbeat in the city," affirming that "it is warm and gentle" and that he would make a better doctor than Hunter.

To understand Leorio as a character it is important to understand his past. Leorio once lost a close friend, a boy named Pietro, to a debilitating illness. Leorio feels deeply regretful for not having been able to save his friend, since the illness was completely curable but required a surgery that he could not afford. Therefore, he aspires to become a doctor, one who not only cures the sick of their illnesses but also works pro bono for people who cannot afford it. In this sense, his seemingly superficial reason for joining the Hunter Exams in pursuit of great wealth takes on a more noble justification: the money he earns is used not only to fund his medical studies, but also to pay for medicine and other miscellaneous expenses when treating those who cannot afford it.

In terms of abilities and power level, you could say that Leorio's power is centered more on his influence and empathy than on combat abilities. He has shown us how he is capable of earning the trust of even the strongest, and how he is capable of mobilizing the masses. His position as a member of the Zodiacs is not because of how strong he is, but because of how much his fellow Hunters trust him. Of course, that position gives him certain advantages and authorities, allowing him to give orders even if his physical or Nen power does not back him up.

Leorio's actual combat abilities are unknown. During the Hunter Exam, he was able to survive being struck by one of Hisoka's cards, although he was still injured, and Netero declared that his combat prowess was superior to Bodoro's. He left a strong enough impression on Hisoka to be considered an opponent worth giving the chance to "ripen." Despite being moderately observant, Leorio's temper often leads him to act impulsively, and we have not actually seen him do more than land a fairly satisfying punch on Ging using his Nen ability and catching him off guard, although it is clear that Ging let himself be hit in order to make Leorio look good.

As a professional Hunter and Nen user, Leorio has above-average perception, strength, speed, and reflexes, and even among average Hunters he could be considered someone slightly skilled; it is only when we compare him to his three other protagonist companions that he begins to look weak. Leorio is also a specialist in the use of knives and can throw them with enough force to pierce through stone pillars.

Of course, his medical knowledge is quite impressive thanks to his studies. It has been said that his first-aid skills are the best there are, and he is capable of identifying when people are faking unconsciousness just by examining them.

In terms of his Nen, Leorio is an Emitter who leans toward Enhancement. Because he postponed his training in order to apply to university, by the time he reunited with Gon and Killua in Yorknew City, he could only use Ten and was unaware of the existence of other techniques. It is possible that he learned Zetsu in a single day, since he managed to sneak up on Kurapika. However, during the Election of the 13th Chairman, it was shown that Leorio had improved greatly, developing at least one Nen ability. According to Ging, he might also possess another ability that earned him the praise of one of the most skilled Nen users in the world. Ging is of the opinion that Leorio's Nen ability was strongly influenced by his studies in medicine.

His Hatsu is the Remote Punch. After striking an object in his proximity, Leorio emits his aura in a line that travels along a surface from the point of impact to a desired location. A wormhole-like circle is generated, from which a fist emerges that strikes the target with an upward hook, extending far beyond the length of a normal arm. Ging, who imitated this technique, demonstrated that multiple blows can be emitted by striking a surface several times, although it is unknown whether Leorio can do the same.

It is an interesting ability with great potential for surprise attacks or even support to help his companions, and this is without mentioning its possible medical use, perhaps being usable to perform a non-invasive surgery on a patient, and maybe even to cure illnesses with surgeries that were previously impossible. This is clearly what Leorio seeks with his technique, even if unconsciously, thanks to his great motivation to save others.

As you can see, Leorio is much more than a mediocre fighter. He is the one who cares the most about his friends, and the only one in the main group who is truly altruistic in his motivations and actions. His attitudes and actions have not gone unnoticed and have earned him praise not only from Ging but from the rest of the Zodiacs, and he has become, almost by accident, a key figure in the world of Hunters.$grulla$, $grulla$Leorio$grulla$),
  ('cmnn877dd0017cndeofhwjm10', $grulla$In Jujutsu Kaisen we always center the conversation on cursed techniques. The broken abilities that define the power of most characters, and that give versatility and creativity to Akutami's world. The exceptions to this rule are few, and most of them focus on the completely opposite side, or on heavenly restrictions that entirely remove the possibility of using techniques with cursed energy in exchange for powerful physical abilities, as with Toji and Maki. However, there is a third option that we know of in very few characters, but through which it is possible to reach a great level of power and be a fairly strong sorcerer. This is through the mastery of martial skills mixed with specialization in a type of technique that any sorcerer can learn, the Simple Domain, or more specifically the New Shadow Style mastered by Atsuya Kusakabe.

Technically, Kusakabe is a teacher at the Tokyo Jujutsu High, but it doesn't seem like his role is an important part of his character, since Kusakabe is mainly characterized by being a fearful person who is focused on his own self-preservation as his top priority. He is also willing to be deceptive to save his own skin, as was shown during the Shibuya Incident, where he repeatedly lied to Panda to keep him close for safety, while steering him away from where Gojo was sealed in order to avoid facing special grade curses. This shows that he isn't the most responsible person in the world, and he tends to worry more about himself than about his students or colleagues.

However, he also has a brave side, as was seen when he protected Miwa from Kenjaku's Uzumaki, which also shows that he is capable of setting aside his selfishness and having a heroic side as a teacher.

Kusakabe is not one of the central characters of Jujutsu Kaisen, and very little is really known about him beyond his abilities and techniques. He is the uncle of Takaba, a dead child whose personality now inhabits one of Yaga's cursed corpses, and we know that he has a younger sister whom he cares about quite a bit, but this doesn't give us much material to focus on.

Kusakabe's main point of interest is his peculiarity of being a first grade sorcerer despite not being able to use cursed techniques. This particular level of power warrants taking a closer look at him.

Despite not possessing an innate technique, Kusakabe is a respected grade 1 sorcerer and a master swordsman of the New Shadow Style. Mei Mei considered Kusakabe to be the only sorcerer of his grade who reached that rank without an innate technique. According to her, according to Kento Nanami and Satoru Gojo, Kusakabe is the strongest grade 1 sorcerer. Satoru specified that his statement might not be accurate if the sorcerers of the Three Great Families were taken into account.

Despite such praise, Kusakabe openly admits on several occasions that he has no chance of defeating a special grade curse and avoids them at all costs. However, he is completely certain that he can defeat other adversaries such as the curse users Toshihisa Negi and Manami Suda, whom he considers to be below his level.

While several jujutsu sorcerers in training were struggling to obtain Kenjaku's Prison Realm, Kusakabe stepped in just in time to save the lives of all of his allies. Even Kenjaku commented on Kusakabe's knowledge of the New Shadow Style, seemingly as a sign of respect for his skill.

Kusakabe's swordsmanship is his main weapon in battle, relying heavily on his physical prowess. In combination with the swordsmanship techniques of the New Shadow Style, he has demonstrated a high proficiency in handling his sword. Using the Battō style, Kusakabe quickly dispatched three curse user henchmen in an instant.

As a grade 1 sorcerer, Kusakabe possesses respectable levels of cursed energy. To compensate for his lack of an innate technique, Kusakabe has mastered the New Shadow Style. This requires finely controlled applications of cursed energy, such as casting a Simple Domain and coating the blade of his katana with cursed energy. Kusakabe also has a sharp sense for judging the strength of his opponent, being able to recognize someone of his level versus a special grade in an instant.

Kusakabe's Simple Domain is an application of a barrier technique to coat his body or his sword and thus increase his power, restore its form, or repel other barriers such as, for example, a domain expansion.

During the peak era of jujutsu in the Heian Era, Sadatsuna Ashiya created the "domain for the weak" with the purpose of protecting his followers from curses and curse users. Binding vows were established that prohibited teaching the Simple Domain to outsiders, but other sorcerers saw the technique in action and were able to copy it for themselves, something the vows did not account for.

Created as a counter to domain expansions, the Simple Domain neutralizes the guaranteed-hit function of a domain by affecting its barrier and not the cursed technique imbued within it. However, against a proper domain expansion, the Simple Domain can only hope to buy time for its user. Powerful domains can destroy simple domains in a matter of seconds.

The barriers of the Simple Domain can be customized with different rules and binding vows to affect those who find themselves inside it, both the caster and the target.

Kusakabe's application of the Simple Domain in his swordsmanship is similar to what we have seen with Miwa but on a much higher level; it can be said that he is the greatest expert of this application. This allowed Kusakabe to protect himself from Kenjaku's Uzumaki and from Sukuna's slashes, incredibly high feats that demonstrate the fine control he has over his barriers as well as his skill and perception.

In addition to this, Kusakabe mixes the New Shadow Style with his named sword techniques to give specific effects to his Simple Domain. These are:

Iai Battō: This technique consists of covering the blade of his katana with the barrier of the Simple Domain, increasing the speed with which the sword comes out of its sheath. This makes it the fastest technique of the New Shadow Style, and it manages to catch countless opponents off guard, as they do not expect this extreme level of speed.

Iai Night Moon Sword: This stance activates a defensive Simple Domain on Kusakabe's sword. While inside the Simple Domain, Kusakabe's cursed energy output is increased while the cursed techniques that intrude upon it are slightly weakened. By incorporating an original program into the Simple Domain, Kusakabe can automatically intercept anything that enters the Simple Domain with his katana.

Blurred Moon: With this technique Kusakabe can use the Simple Domain to reform part of his katana with cursed energy in case it is destroyed; this allows him to cover one of his greatest weaknesses, the fact that he uses a normal katana that can be destroyed. Although it is important to mention that Kusakabe's use of cursed energy raises his katana to the level of a high-level cursed tool.

As you can see, just because Kusakabe can't use an innate or inherited cursed technique, it doesn't mean he is weak; on the contrary, it is easy to underestimate him, and the speed of his techniques mixed with his mastery of the New Shadow Style are capable of taking advantage of any opening in the opponent and even finishing them off in a single blow. The mere fact that Kusakabe was able to stand against Sukuna for as long as he did makes him, as his fellow teachers said, one of the strongest first grade sorcerers to ever exist, and this with the simple mastery of a barrier technique and his skills with the sword$grulla$, $grulla$Kusakabe$grulla$),
  ('cmnn8773r0015cnde1a2pm1i4', $grulla$Motivations are inseparable parts of characters. Those aspects of their past, or of their desires for the future, that move them and shape their personality are what make them who they are, and there is no more important motivator in the world of Hunter x Hunter than revenge. Revenge for your loved ones, revenge for yourself, or revenge for your clan. This powerful feeling is enough to bring out a person's potential, and in Kurapika's case, it is his entire being, what dictates his every move and even what limits and empowers his hatsu and all of his Nen abilities.

Kurapika is my favorite character in Hunter x Hunter, and his Hatsu is my favorite Nen ability in the entire series, and this is due to its complexity but also its focus toward a single objective. Kurapika is the last survivor of the Kurta clan, or the clan of the scarlet eyes, after his entire clan was hunted down for their valuable eyes. This naturally explains his character's obsession with recovering the precious relics of his fellow clansmen, and it is all he can think about most of the time.

However, this does not mean Kurapika is one-dimensional; if anything, I would dare say that the internal conflict he shows us, and his attitudes toward the different kinds of people he encounters throughout the arcs, make him one of the most complex and profound.

We first meet Kurapika in the Hunter Exam arc as an intelligent, kind, and honest boy who makes friends easily and has an incredible latent talent as a Hunter. However, even in this arc, the darkness within him suddenly begins to show whenever the subject of his eyes or his clan is touched upon, and it reveals his uncharacteristic loss of self-control when it comes to this part of his being.

Of course, in York New, Kurapika could be considered the protagonist, and it is here that we learn the extent of what this boy is capable of doing and sacrificing in order to achieve his revenge. This dark arc perfectly reflects the darkness and loneliness in Kurapika's soul, and just as the Hunter Exam arc showed us his light with touches of darkness, this arc shows the black void in his heart, but not without showing us, in his interactions with Melody and his companions, that there is light in there too. These small displays of kindness show us the other side of Kurapika that we surely forget beneath his hatred and bloodlust, and they make us wonder which side is the true one.

From this point on Kurapika becomes more mysterious; we are mostly absent from him for the rest of the arcs. However, after passing the endpoint of the anime adaptation and venturing into the manga-exclusive arcs, we return to Kurapika as protagonist, and we come to understand not only his dark and light sides, but his intelligence, his tactical skills, and the sheer versatility of his ability and Nen.

In terms of power level, Kurapika's powers increase enormously as the series progresses. Hisoka was the first to take an interest in him, classifying him as one of the "green fruits" with vast potential. Although he was weaker than Killua at first, by the Yorknew arc he had become stronger than him thanks to his Nen abilities. He is one of the few characters to have killed a member of the infamous Phantom Troupe, and a very powerful member at that, in Uvogin. His exceptional intelligence is on par with his great combat prowess and his iron will, which stems from his desire for revenge. He is also a very versatile fighter, as he has been seen wielding different weapons. In his confrontation with Uvogin, he used his chains both at range and in close-quarters combat, and he has been seen using a Bokken, knives, Shuriken, and even firearms such as pistols.

Of course, if we are going to talk about his power level, we cannot leave aside his Scarlet Eyes. When a member of the Kurta Clan becomes enraged, their eyes turn a vivid shade of red, which triggers an astonishing increase in physical strength. In this state, even as a child, Kurapika could gain the advantage in terms of speed and strength against three adults and overpower them easily. However, Kurapika admitted that when his eyes turn scarlet, he loses all restraint and rationality and becomes primal, which also happens whenever he sees a Spider. Furthermore, excessive use of his Scarlet Eyes can have serious repercussions on his health, as doing so left him incapacitated and feverish for more than a day, with Melody's Nen ability unable to bring his body temperature down. His current limit is about 3 hours, after which the pain and fatigue become too intense and he passes out for three times as long. Kurapika also speculates that prolonged repeated use, or uses induced by stealing particularly powerful abilities, may cause him to reach the limit before 3 hours have passed. At some point during his Nen training, Kurapika learned to turn his eyes scarlet at will and gained the ability to control his emotions.

Kurapika is one of the most brilliant characters in the series. Because of this, he was named leader of Neon's bodyguards after Dalzollene's death. He outmaneuvered minds on the level of Chrollo with carefully planned strategies, and his predictions have rarely turned out to be wrong. He also has immense knowledge on many subjects, ranging from psychology to other cultures, from history to criminology, a quality that surprised his companions when he was just a child. Due to his thirst for new knowledge, he learns quickly and has an impressive memory. Kurapika's analytical skills are so outstanding that they have led to a rumor spreading among the assassins of Muherr that he is capable of reading minds. While searching for Halkenburg in Kakin's bodyguard registry, he used the vaguest of clues to pick out the person he felt was Halkenburg, something Oito praised.

Kurapika can formulate flawless plans even in combat to fully exploit his opponent's weaknesses. His intuition is combined with his logical thinking and meticulous preparations. Although he can stay calm in desperate situations, he can barely stick to his own plan when it comes to the Phantom Troupe, to the point where he might even lose control and endanger not only himself but also his friends. On the Black Whale, he showed greater composure than before and pulled off his greatest strategic feat to date, becoming the linchpin of a stalemate, or at least an obstacle, in the succession contest with an endless series of tactics, mixing truth and lies, secrets and deliberately disclosed information. His disclosure of the existence of Nen and its categories constituted the biggest shift in the succession contest, forcing an impasse and increasing the survival odds of the lower-ranked princes.

As far as his Nen goes, Kurapika is a Conjurer, a Nen user who can create objects out of nothing according to his imagination, but he becomes a Specialist when his eyes turn scarlet. He learned Nen in very little time and is considered a highly skilled user. In terms of theoretical knowledge, he can divide Nen learners by aptitude, and he is an expert in the mechanics of Nen Limitations and Manipulation. Kurapika has Nen abilities that incorporate elements of Emission, Manipulation, and Enhancement; in addition, he has shown proficiency in Transmutation, proving to be a complete Nen user and one of the few who can access all six categories of Nen. The weapon he conjures is unique: five chains that extend from each finger of his right hand. Some of the fingers were specially designed to take revenge on the Phantom Troupe. To increase the effectiveness of his chains against them, Kurapika imposed strict Limitations on the use of his chains. Since the chains are materialized, their size and length can be controlled to a certain extent. He is able to hide his chain through In to bind his opponent without them realizing it until it is too late. Kurapika is also proficient in other branches of Nen, such as Shu, which, combined with Emperor Time, gives his chains the ability to break rocks. He has reached such a high level of skill that he can remain in a state of Ten without conscious thought.

By using a Limitation that puts his own life at risk, his abilities received a great boost. In fact, one of his chains is so strong that Uvogin, an experienced fighter, assumed it was a real chain that Kurapika was manipulating. The combination of his Limitation, the increase in ability granted by his Specialization power, and the aura boost granted by his Scarlet Eyes allowed him to close the gap in strength against a master Enhancer like Uvogin. Repeated use of his Scarlet Eyes combined with Nen takes a great toll on his mind and body, causing a high and incapacitating fever that, after Pakunoda's death, lasted several days and could not be relieved by Melody's flute.

Let's talk about each of Kurapika's chains.

Dowsing Chain:

A chain that ends with a small ball-shaped weight, which Kurapika frequently uses in combat for both offensive and defensive purposes. Its main use is as a tool for pendulum dowsing, with the ball moving according to Kurapika's objective at any given moment. As such, it is useful for investigation, since the chain can be used to determine the location of missing persons (moving in their direction) and to identify whether someone is lying (moving back and forth). If the chain's ability is used on a group, it works best if the people being questioned answer one at a time. Under normal conditions, Kurapika must be directly in front of the target for lie detection to be effective; however, when Emperor Time is active, he can also use that ability through video recordings, as long as he has met the subject before. Kurapika himself does not know how this aspect of his power works; his guess is that, through the transmission of the chain and extreme concentration, he can unconsciously detect subtle signs that someone is lying.

Chain Jail

An extremely durable chain with a hook on the end, whose sole purpose is to capture members of the Phantom Troupe and deprive them of their freedom. It forces captives into a state of Zetsu, shutting off their aura and preventing the use of Nen abilities; consequently, the only way to escape this chain is through brute force, although not even Uvogin, the physically strongest member of the Spiders, could break free from it. The chain manifests so quickly that Kurapika can completely immobilize a distant target in half a second. To create the jail, Kurapika imposed the Limitation that it can only be used on members of the Spiders, with the additional stipulation that violating this rule will result in his death.

Emperor Time

When Kurapika's eyes turn scarlet, he changes from a Conjurer to a Specialist. This ability allows him to use all types of Nen at 100% efficiency (for a Conjurer). Kurapika explains this using the terms "Level," "Strength," and "Precision": his "Levels" in the various Nen categories remain the same during Emperor Time, but his "Strength" and "Precision" for each category are raised to 100%. Thus, if Kurapika's "Level" in Conjuration was 10, his "Level" in Emission (the polar opposite aura type) would still be 4 at most, but his "Strength" and "Precision" in any Emission ability would increase from 40% to 100%, making him an even match against a Level 4 Emitter. However, the price to pay is considerable, since every second spent in this mode reduces Kurapika's lifespan by one hour.

Holy Chain

Through his cross pendant, this chain heals wounds by drawing on Enhancement-type Nen. When Kurapika is in his Specialist state, the chain can heal serious injuries, such as a fractured arm, in a matter of seconds. Apart from this it does not seem to have many other uses, but having a healing ability is extremely useful for Kurapika given the level of danger of his main mission.

Judgment Chain

Through the blade at its end, called the stake of vengeance, this chain enters a victim's body and coils around their heart. Kurapika then declares a binding rule that, if violated by the victim, causes the stake to pierce their heart and kill them. Kurapika himself has a blade around his own heart, which he used to set the limitations on the use of the Chain Jail ability. He is able to issue at least two commands per stake, and he can dissolve the chain at will, and he is certain that he would be alerted if a member of the Spiders removed it. Due to Kurapika's low affinity and mastery in Emission and Manipulation, the Judgment Chain can only be used during Emperor Time.

Stealing Chain

With a syringe-shaped end, this chain, upon piercing a target's body, extracts their aura and steals one of their Nen abilities. While their aura is being drained (a process that seems painful), the target is forced into a Zetsu-like state. Afterward, the target cannot use the stolen ability until it is returned to them. There are no conditions for stealing an ability other than piercing the target with the syringe: so far, Kurapika has stolen two abilities, one after the owner's Nen type was revealed and the general mechanics of the ability explained, and another that was about to be used without any prior knowledge. The death of the original owner does not result in Kurapika losing possession of a stolen ability.

Stealth Dolphin

By activating Emperor Time, Kurapika can summon a dolphin-like Nen beast with a syringe on each pectoral fin that is visible and audible only to him. This construct can "equip" and analyze the stolen ability, informing Kurapika of its name, functions, and conditions. Kurapika can then use the stolen ability himself or lend it to another person, including non-users, by jabbing them with the Stealing Chain. In the latter case, a listening device is conjured in that person's ear, allowing them to see the dolphin and communicate with it through telepathy. The dolphin can advise the new recipient on how to use the ability, and it will use the ability itself when ordered to by the recipient of the lent ability. When Kurapika, or someone he has lent an ability to, activates it, it is fueled by the aura that the Stealing Chain extracted from its owner, ensuring it is used with the original power.

A side effect of the Stealth Dolphin is that when it is used on a non-user, it allows them to see aura and, after the lent ability has been activated, it half-opens all of their aura nodes, essentially making them Nen users, although training is still required to control the flow of aura and prevent it from leaking.

If Kurapika equips the dolphin with a stolen ability and transfers it to another person, he can use the Stealing Chain again, but the transfer does not allow him to leave Emperor Time until he calls the dolphin back, and the stolen ability must be used in order to do so. Regardless of who controls the stolen ability, it can only be used once, after which it returns to the original user. As a drawback, as long as all stolen abilities have not been returned, Emperor Time will remain active. The dolphin will regularly notify Kurapika of how long it has been active unless it is put into standby mode, in which case it can be made to disappear. If Kurapika passes out while another person is using an ability he has lent them, that person will pass out as well.

Of course, we cannot talk about the Stealing Chain and the Stealth Dolphin without talking about Kurapika's stolen abilities, so let's go through them quickly:

Little Eye:

Kurapika stole this ability from Sayird. With it, the user throws a ball of aura at an insect or any other small, living creature, capturing it and gaining control over it. The largest creature the user can control is about the size of a hamster. The user gains knowledge of everything the manipulated animal sees or hears. For this reason, the ability is particularly useful when used on flies or mosquitoes, but since they have many natural predators, they tend to die while under the effect of the ability. Faster animals can be difficult to catch. The ability cannot be used on living beings created through aura. The controlled animal retains the user's ability to see aura. This ability seems to consume very little aura, since even a person who was not originally a Nen user could maintain it for an hour without noticeable strain. Moreover, it does not deactivate if the user passes out.

Air Blow

Kurapika stole this ability from Vincent. Little is known about it. The original user tried to activate it through his left palm to break the guard of a Nen user who was capable of stopping bullets with his aura. It seems it does not require direct contact with the target to work, and we can infer that it is a blow of air that can stun or open up an enemy's guard.

Erigeron

Lastly, Bill voluntarily allowed Kurapika to steal this ability, which dramatically accelerates the growth of living beings when the user brings their palms close to them. Its main use is to develop other people's Nen abilities, although the effects on people with little talent are quite mild.

As you can see, Kurapika's Nen abilities, like his character, are extensive and complex, which sometimes makes them a little difficult to understand. However, the objective of both is clear: to wipe out the Spiders and recover the scarlet eyes of his fellow clansmen, and although he takes it a bit to the extreme, I think we can all identify with Kurapika a little, whether in his darkest moments or his most illuminated ones.$grulla$, $grulla$Kurapika$grulla$)
) AS v(id, body, title)
WHERE r.id = v.id;
