-- Batch 6: 4 reviews. Run this whole file as one statement.
UPDATE "Review" AS r SET "contentEn" = v.body, "titleEn" = v.title
FROM (VALUES
  ('cmnn875sj000vcndeovuh0au4', $grulla$Cursed spirits are almost as important as jujutsu sorcerers when it comes to making the world of Jujutsu Kaisen interesting and giving it character as a whole. These innate antagonists have development almost as deep as the protagonists, and some of them show us ambitions, goals, and personalities that even surpass some of the good guys. Among them, Kenjaku's underlings are the ones who have been given the most screen time, and therefore the ones we know best, and none of them is as fiery and passionate as the unregistered special grade volcanic curse. Jogo.

Taking into account the wide spectrum of cursed spirits that have been shown in the Jujutsu Kaisen anime so far, there is no doubt that Jogo leans toward the extreme in practically every aspect. With a fiery temper matched only by the explosive power of his innate cursed technique, Jogo is a character who never walks away from conflict of his own volition, even in situations where he is completely outmatched.

In fact, alongside Mahito, we could say that Jogo is the most recognizable and iconic cursed spirit in Jujutsu Kaisen, and despite having lost the two main fights we saw him take part in, don't think for a second that Jogo is weak. What's more, excluding Sukuna, you could say that Jogo is the strongest cursed spirit we've seen; he's just extremely unlucky to have fought against the two most broken characters in the entire series. If you want proof of his true power against more standard-level characters, ask Nanami, Naobito, or Maki how they measure up against him.

Jogo is defined by his pride as a cursed spirit. He is an intelligent being who considers himself firm in all his beliefs, willing to give his life as long as his goals would be achieved in the long run. On a personal level, Jogo is always grumpy, irritable, and very arrogant.

Jogo believes that cursed spirits are the true humans and that they are the ones who will inherit the earth. He sees humans as creatures made of lies who try to hide their true nature with the positive emotions they display. Curses are composed of negative emotions, which Jogo sees as pure intentions, and so he believes that curses born from that truth are the purest forms of humans and that the false ones should be eliminated. To achieve this, Jogo and his companions agreed to ally themselves with Pseudo-Geto, or Kenjaku, despite him being technically a sorcerer.

Although Jogo is clearly an evil character, his relationship with his fellow cursed spirits is one of camaraderie, friendship, and even family. He sees Dagon and Hanami as his best friends, and his dynamic with Mahito is rivalry but friendly. This contrasts with his attitude when we see him as a villain, when he shows no mercy to humans, being arrogant while crushing them like flies.

In terms of power level, Jogo was one of several unregistered special grades that appeared around 2018. He was born from humanity's fear and negative association with volcanoes and other fire-related natural disasters. This resulted in a highly intelligent cursed spirit with massive levels of cursed energy, even for a special grade. Kenjaku generously placed Jogo at the same strength level as eight or nine of Sukuna's fingers. Although Jogo was no match for overwhelming powers like Gojo and Sukuna, he still far surpassed even the most talented sorcerers and other special grade curses.

Non-sorcerers catch fire in Jogo's very presence if he simply activates his cursed technique. Jujutsu sorcerers who enter his domain would suffer a similar fate. In Shibuya, the Zenin Team and Nanami considered Jogo to be far more powerful than Dagon, whom they had just faced with great difficulty. Jogo defeated Nanami, Maki, and Naobito in mere moments using his superior speed and power. This left half of Nanami's body charred, gave Maki permanent scars, and caused serious injuries to the head of the Zenin clan that soon cost him his life.

Despite not being able to match Sukuna with fifteen fingers absorbed, Jogo's strength was still acknowledged by the King of Curses. Sukuna admitted that Jogo's maximum technique could have hurt him if it had landed. Across all the opponents Sukuna has faced in over a thousand years, Jogo stood out as one of the strongest, a great endorsement of his power overall. Kenjaku even emphasized that he would have liked to absorb Jogo with Cursed Spirit Manipulation and acquire his technique, that's how powerful it was.

Innate cursed technique: Disaster Flames

This technique allows the user to form and control both flames and lava. Its capabilities are not limited to close combat alone, but can also be used telepathically, activating the technique directly on or near a target.

The flames are immensely powerful, capable of instantly killing non-sorcerers and seriously wounding sorcerers. These flames are also visible to non-sorcerers and possess properties similar to real flames. A person with superhuman physical resistance can completely survive these attacks thanks to their body, while a sorcerer's tolerance to curses might not be enough to save their life.

The technique also grants Jogo the ability to telepathically create volcanoes on surfaces. These volcanoes are capable of firing powerful lava at the user's target.

Jogo also has some named techniques that make use of his cursed technique, such as the Ember Insects, with which Jogo conjures small flying insects from his head, whose stingers produce a loud noise upon impact before exploding into flames.

Of course, we can't forget that Jogo is one of the few characters who have shown us the maximization of their technique, showing us the maximum technique, Meteor.

As its name indicates, Maximum: Meteor is a maximum cursed technique that conjures a flaming meteorite that Jogo launches as a projectile. It is relatively small compared to real meteorites, but massive enough to cause widespread devastation on the scale of an entire city. This technique is so powerful that it could even seriously wound Sukuna himself, who was forced to dodge it before finishing off Jogo.

Let's also not forget his domain expansion: Coffin of the Iron Mountain.

The environment built by this domain resembles the interior of an active volcano. It is a sealed stone chamber with large fissures in the walls and floor that expel large portions of magma. This produces such great ambient heat that the average jujutsu sorcerer would catch fire upon entering the domain.

Coffin of the Iron Mountain is a lethal domain that includes a guaranteed hit. The user can command the molten rock extending from the environment to strike his opponent with an attack that cannot miss; of course, if Jogo manages to land this guaranteed hit against almost anyone, his opponent would be instantly burned to a crisp. Unfortunately, when we saw him use the technique, his domain was overwritten by Gojo's, not allowing him to show its true effect.

Last but not least is the Domain Amplification that Jogo is capable of, a technique of manipulating compact domains that allows Jogo to amplify his cursed energy and form an aura capable of neutralizing the effects of a domain expansion's guaranteed hit. Additionally, this technique neutralizes the technique of whatever it touches, providing great flexibility in combat and, in theory, allowing Jogo and the other users to even strike Gojo through his Limitless. Unfortunately, this technique comes with a giant drawback, since it does not allow the user to use their innate technique while it is active, limiting them to hand-to-hand combat.

As you can see, despite his defeats and humiliations throughout the series, Jogo is a strong contender for one of the most powerful cursed spirits ever created, and his flame and lava control abilities are nothing to laugh at. Additionally, his development as a character, his personality, and above all his goals clearly explained to us as the audience make him a character who was incredibly interesting to see expressed in the work, and certainly make him someone relatable to many and even the favorite of some.$grulla$, $grulla$Jogo$grulla$),
  ('cmnn875hb000tcndevfvi9496', $grulla$There are characters that make us uncomfortable. Characters whose mere presence makes you feel that something is wrong, and that makes your skin crawl just from looking at them. These characters are usually physically grotesque and villains incarnate. However, Hunter x Hunter has my favorite example of this type of character, and not only is he not necessarily a villain, but he is the favorite character of many, many fans, and one of the most important in the entire story, both for explaining how Nen works and for the evolution of the protagonists. Of course, I'm talking about the sociopathic magician, Hisoka, the owner of the legendary Nen ability Bungee Gum, a technique with the properties of rubber and gum.

Hisoka is portrayed as someone completely selfish and self-centered; he does what he likes as long as it brings him pleasure in some way. His insatiable love for spilling the blood of powerful fighters in combat and his enjoyment of extreme pain while doing so feed his apparent sadomasochistic desires. So that the main protagonists can reach their full potential (in order to enhance the pleasure of killing them later), Hisoka allows them to live in situations where he could easily kill them. Likewise, he gets excited about meeting new people he considers worthy of fighting, or anyone with the potential to be a good fighter and entertain him in the future. The thrill of fighting strong Nen users in tactical battles and near-death experiences is an orgasmic experience for him. This is likely one of the reasons he goes to such lengths to find new toys to play with. If they break, he loses interest in them or kills them before setting out to look for more potential prey.

With his manipulative and self-centered nature, Hisoka is essentially a murderous sociopath. Although he likes Gon, Killua, and many others, he has said that for him, what is valuable one day could easily turn into garbage the next, and he will not hesitate to kill anyone if they don't meet his standards. He doesn't care about what happened in the past, since he is only interested in what could be fun for him in the future or the present. Although Hisoka's nature tends to be malevolent, he is not an indiscriminate killer. He has no problem killing anyone regardless of their age or sex; however, he only kills people who are in his way or those he considers "worthy." As such, his character is more simply amoral than completely evil. He even helps the protagonists if there is "fun" in doing so or if it will make them stronger, leading to a more entertaining fight in the future. Above all, Hisoka only cares about having fun and getting a good challenge, which may or may not involve killing people. He has a bad habit of skipping the Spiders' meetings. He can also be a capricious liar and tends to scare or play cruel pranks on his victims. Merely witnessing their uncomfortable expressions because he makes them nervous pleases him. His chaotic nature is inherent in everything he does and makes him dangerously unpredictable.

Hisoka has shown a morbid attraction to fighting powerful fighters, or people with Nen who have the potential to become strong, which is expressed through barely repressed murderous tendencies; neither age nor gender seems to influence his desire to fight them. He has expressed his desire to fight or kill random victims just to quench his thirst for blood. After his defeat at the hands of Chrollo, Hisoka's sociopathic nature has worsened, with him vowing to kill every member of the Phantom Troupe, even if they were defenseless, and stating that he will no longer allow his opponents to fight on their preferred terms. However, he temporarily spared Machi, who has been an implied interest of Hisoka's as a possible opponent he likes to flirt with or as a romantic interest, although he said it was so that she could warn the Troupe of his intentions.

Hisoka often exhibits androgynous characteristics throughout the series, manifested in his use of "feminine" shoes and a seductive speaking style typically reserved for women in Japanese. In the manga, he ends almost all of his sentences with a playing card symbol.

Despite his calm and composed personality, he can express his emotions comically in some situations. One example is when Gon, being honest and rather innocent, asks him why Hisoka was on Greed Island. Another example is his surprised face when he learns that he could not fight against Chrollo after Kurapika's Chain Jail.

Hisoka is famous for his elegant, cruel, and deceptive combat ability, which has earned him the rank of Floor Master, and he has proven to be a lethal adversary. His tremendous physical abilities and combat skills make him extremely dangerous in a fight, and his Nen expertise, tactical genius, and flexibility allow him to quickly adapt to changes in circumstances. Among the opponents he has defeated are the former Phantom Troupe member #4 and the Single-Star Blacklist Hunter, Bushidora, killing the latter without sustaining any injury. He has expressed dissatisfaction with the power level of most Professional Hunters, which led him to consider fighting the Zodiacs to find a new challenge, and indeed, he was able to effortlessly dispatch several Hunters in a short period of time. Illumi Zoldyck, who was estimated by the magician to be even more formidable than some Zodiacs, was careful about facing Hisoka, and even the leader of the infamous Phantom Troupe considered it prudent to prepare a strategy and gather Nen abilities before facing him in order to secure his victory, declaring that Hisoka set a new record for the number of abilities he needed to kill someone.

Hisoka is also a skilled magician and often uses Nen to perform his tricks. His skills in misdirection and his astonishing dexterity find applications in combat, and their combination allowed him to triumph against Kastro. This latter talent also allowed him to catch Togari's spinning knives on the first try, while their owner needed six months to do so. In addition, Hisoka has a certain degree of computer proficiency, which he used to track down Gon and Killua after they bought airship tickets online. By forming a circle with his index finger and thumb and looking through it, he can enhance his vision. It is unknown whether this technique is achieved with Nen, or whether Hisoka can simply enhance his sight by concentrating. Hisoka's enthusiasm for battle often causes him to take more damage than he would if he fought seriously from the start. In fact, his willingness to let Chrollo choose the place and time of their confrontation, as well as to adapt to his pace in the early stages, almost led to his demise.

Hisoka is a Transmuter gifted with a powerful and sinister aura that unsettled Wing and Gon even after the latter had learned Nen. He manifests his high level of skill in his natural category mainly through his Nen ability, Bungee Gum, but he has also proven to be very skilled at controlling the shape of his aura, which is a Transmutation skill. This aptitude may be what allows him to extend threads of elastic aura over distances of several meters without throwing them, which makes their application more subtle. He is also very well versed in Conjuration, the Nen type of his second ability, as well as in Emission and, apparently, in Enhancement. He uses the former to keep aura around projectiles, as well as in conjunction with Bungee Gum, to separate the ability from his body.

His affinity for Enhancement manifests mainly as a notable level of durability. Hisoka survived multiple Nen-enhanced blows from Kastro, an Enhancer, without using his aura to defend himself. Although he was briefly stunned, Hisoka suffered no visible damage from most of Chrollo's attacks, one of which can supposedly decapitate a person with a knife-hand strike, despite the fact that Hisoka could not predict them and was therefore unable to protect himself properly. He appears to have resorted to Manipulation on one occasion, taking advantage of the boost enjoyed by Nen after death to impart an automatic command to his Bungee Gum.

Aside from Hatsu, Hisoka is capable of using at least Ren, Gyo, and Ken, which allowed him to survive multiple explosions of The Sun and Moon detonated in his proximity, although one of his legs was severely mutilated. Like many other high-level Nen users, he can maintain a state of Ten at all times. He is also likely proficient in Zetsu and Ko. The two techniques he employs most frequently are Shu and especially In. With Shu, his poker cards can easily cut through bone and concrete even when he is not holding them. When he applied it to a severed human head, it carried such force that it pulverized other heads it came into contact with, incapacitated several puppets with a single throw, and injured a Nen user of Chrollo Lucilfer's caliber without sustaining the slightest damage, whereas it would break immediately if it were not wrapped in aura. While Hisoka prefers Shu for direct attacks, In is at the center of his strategies, as he combines the technique with Bungee Gum to set elaborate and deadly traps.

Hisoka's Nen prowess is further supported by his knowledge of more abstract notions, such as the strengthening of Nen after death and Exorcism. He also devised the concept of "Memory Overload" and a system for guessing an individual's Nen type from their personality, which, despite him calling it unreliable, has proven to be correct several times.

Hisoka's main ability allows him to make his aura sticky and elastic. Its extreme durability, flexibility, and adhesive properties make it an exceptionally versatile ability with various offensive, defensive, and supplementary applications. He can activate it from his fingers, hands, and feet. He can attach it both through physical contact and remotely, extending it toward the target, which makes it very difficult to avoid. He can command it to contract at will, and it retracts with greater force the more it is stretched. It is so resistant that it did not break after absorbing the full force of a ball thrown by Gon with Rock, or several of Gotoh's coins, which makes it an effective way to return projectiles to their sender.

Offensively, Bungee Gum can be used to draw the opponent toward Hisoka or to create flail-like weapons. He can also separate it from his body, in which case it will break after a maximum stretch of 10 meters. He commonly separates it from his body to attach projectiles to his opponent, such as his Shu-enhanced cards, while concealing it with In. The combination of this latter technique and Bungee Gum allows Hisoka to create multi-layered traps that all activate at once, killing the unsuspecting opponent in an instant. He has also emitted it to restrain individuals as powerful as Machi.

Bungee Gum also has a wide range of auxiliary applications. Hisoka can attach it to a solid surface to retreat at high speed when necessary. By using it on his feet, he can stick to the ground or run along walls. It is also useful for sticking objects in place for traps or for keeping them held down, even after throwing them. By covering a wound with it, he can instantly stop bleeding. On one occasion, he wrapped his lungs and heart with it to resuscitate himself. By creating non-adhesive aura, he can also replace lost limbs, which can be coiled like a spring to propel himself at tremendous speed.

Hisoka can apply his aura to any smooth, flat surface, such as paper or fabric, and manifest images on it to change its appearance and texture in order to deceive. He can replicate more than a thousand different textures. He has fooled Nen users of the Spiders' caliber with this ability, with none of them realizing that he had used it, whether by sight or by touch. Against Kastro, he used Texture Surprise to hide his wounds and confuse him. It can also be applied to pure aura, such as Hisoka's Bungee Gum, to alter its own appearance. Since aura cannot be detected once Texture Surprise is active, whether through sight, touch, or extrasensory perception, and its effects are also visible to people incapable of using Nen, it is safe to assume that Texture Surprise is a Conjuration ability, which is supported by the fact that it requires Hisoka's direct action to be dispelled and by a verb used in its description.

As you can see, not only is Hisoka extremely versatile and flexible in his thinking and actions, but his Nen ability perfectly reflects his character, being one of the most versatile techniques in existence. Additionally, in my opinion it is the Nen ability that best incorporates the base abilities, and Hisoka excellently demonstrates his knowledge in various situations, truly earning the title of a Nen master, in addition to pedophile, sociopath, and fighting addict.$grulla$, $grulla$Hisoka$grulla$),
  ('cmnn8758h000rcnde5orn3ezg', $grulla$Something we don't see much of in Jujutsu Kaisen is those characters who are completely disillusioned with the reality of the world, and how this entirely shapes their personality and motivations. A clear example is Geto, but aside from him few characters have shown us this kind of change. Recently, however, Hiromi Higuruma has shown us what it means to go from being an idealist to completely losing faith in the system he is part of, and his story reveals the complexity that exists even within the most upright of men when they are pushed to their moral limits, while his cursed techniques are an excellent thematic complement to his character.

Higuruma is one of the most complex characters in the entire series. As a defense attorney, Higuruma was renowned for his extraordinary intellect and his willingness to take on impossible cases in order to defend the unjustly accused. He strove to uphold the ideal that everyone deserves a fair trial under the law. However, when the justice system failed one of Higuruma's clients in a way that deeply shook his beliefs, it triggered changes within the lawyer.

Born in Tokyo, Higuruma began his career as a defense attorney, specializing in impossible cases where his clients were almost certain to be found guilty. Those closest to him considered him a bit of a masochist for taking on such difficult trials, but it was his passion for justice that drove him. With an extraordinarily brilliant mind that earned him praise even in the rigorous world of law school, Higuruma truly believed in protecting the innocent and giving even the accused a chance to prove reasonable doubt.

Over time, the nature of the work and the constant exposure to unjust verdicts took a toll on his mental state. Although he always tried to keep cases from affecting him personally, the expressions of horror on his clients' faces when they were found guilty despite overwhelming evidence in their favor haunted Higuruma. It became too much to ignore after his cursed techniques abruptly manifested during a trial in which clear evidence proved his client's innocence, yet they were declared guilty all the same. This pivotal moment marked a turning point that led Higuruma down a much darker path.

When his most recent client was found guilty despite the overwhelming evidence in their favor, it represented a failure of the justice system that Higuruma had devoted his career to defending. Still trying to come to terms with his newfound jujutsu abilities, Hiromi reacted with anger and pain, attacking the prosecutor and the judge in a moment of rage. This tragic event weighed heavily on him, as taking a life went against his moral code. It marked a shift in his perspective, leaving him disillusioned with the laws of man and disconnected from his former role as a defense attorney. He became generally discontent and detached from society, claiming that he now cared little for anything.

It was during the Culling Game, however, that Higuruma's character underwent another change. Initially viewing it as a way to simply observe how the rules might unfold without restrictions, he encountered Yuji Itadori and rejected his request for points to help stop the game. This set them on a collision course as antagonists. However, Yuji's willingness to confess to a crime he was not guilty of resonated with Higuruma's sense of justice, reminding him of why he became a lawyer in the first place.

With Yuji's innocence mirroring that of his client, who had faced unjust punishment, the former defense attorney had a change of heart. He reoriented himself to once again prioritize protecting the weak. Higuruma's cooperation with Yuji marked an intriguing change that showcased the complexity within this multifaceted Jujutsu Kaisen character.

Upon entering the arena of the Culling Game, Higuruma quickly distinguished himself as one of the best players. With barely any jujutsu experience aside from what he acquired in the short time since his awakening, Higuruma reached a level comparable to that of Grade 1 sorcerers in just twelve days. He exorcised numerous curses and killed at least twenty opponents within the colony.

It was there that he first crossed paths with Yuji. After Higuruma had Judgeman confiscate Yuji's cursed energy and perceived his disadvantage, the powerful sorcerer attacked with lethal intent. Yuji only managed to save himself by demanding a retrial, which halted their battle. This dangerous situation showcased Higuruma's combat prowess and his willingness to eliminate any threat.

From that moment on, Higuruma cooperated with Yuji's goal of stopping the Culling Game, even using his accumulated points to help save trapped civilians. Although they briefly parted ways to atone for their past crimes, Higuruma proved to be a valuable, if unstable, ally with potentially world-class abilities. His interactions with Yuji revealed new depths to this complex character in the series.

At the core of Hiromi's abilities lie his tremendous cursed energy and sharp intellectual talents, having unlocked his powers through natural talent and rapid self-teaching.

His cursed technique is called Judgeman, and it is thematically appropriate given his former profession. Using his vast amount of cursed energy, Higuruma summons a single Shikigami with a terrifying appearance, clearly based on a macabre version of the personification of the law. This shikigami features a set of scales, through which it can measure the opponent's guilt in an arbitrary crime that Higuruma decides to accuse them of. On its own, this technique does not seem to have much practical use; however, in a rather curious case, Higuruma appears to have awakened his domain expansion simultaneously with his cursed technique, and it is this domain that makes his technique and shikigami extremely terrifying.

Within his domain expansion, Deadly Sentence, Hiromi summons his judge shikigami. The domain takes the form of a circular courtroom, with guillotines surrounding a central stage. As the "judge," Hiromi interrogates his opponents while Judgeman observes passively, its verdicts influencing the conditions within the battle. Once an opponent is "convicted," Hiromi gains an advantage by increasing the size of his cursed weapon, the judge's gavel, which he wields with expert martial skill.

This domain is unusual in that it does not contain a guaranteed hit; instead, those trapped within it must follow the domain's rules, which include a complete prohibition of violence inside it. The domain includes a binding vow that requires Higuruma to explain the rules of the trial. First, Judgeman announces the charges against the accused, which can arbitrarily be things they may or may not have done; of course, Judgeman is relatively omnipotent within the domain and already knows whether the accused is guilty or not.

Higuruma will then lay out his case for why his opponent is guilty, and the accused will have the options of remaining silent, confessing, or denying the accusation and presenting their arguments. Should they choose the last option, they will not be able to lie. There is also the complication of an envelope containing additional evidence, which is only revealed at the end of the trial and may change Judgeman's verdict. In the end, if the accused is found guilty, they will then be punished with one of multiple sentences according to the severity of the case. These range from losing all of their cursed energy to the death sentence, which takes the form of a sword of light that will kill anyone it comes into contact with. It is important to mention that if the case is serious enough, both sentences can be handed down at once.

A curious case is that the accused can request a retrial if they believe the verdict was unjust and was made without all the available evidence, which, for example, allowed Yuji to use this for a retrial with Sukuna as co-defendant.

What truly sets Higuruma apart is his genius-level intelligence and his ability to achieve mastery of jujutsu in just two weeks, including barrier techniques. This rapid self-teaching allowed him to develop his own unique domain expansion, demonstrating his immense potential and love for the law.

Throughout the world of Jujutsu Kaisen, Higuruma emerges as one of the most fascinating characters in the series. Starting out as a passionate defender of justice who later becomes disillusioned, he undergoes compelling changes in ideology and loyalty. Although volatile after being betrayed by the justice system he had dedicated his career to defending, Higuruma demonstrates nuanced layers beneath an initial antagonism.

His change of heart and cooperation with Yuji reveal deeper principles of protecting the vulnerable, which first awakened jujutsu in Higuruma. Powerful yet intelligent, threatening yet vulnerable, Higuruma intrigues through a complex humanity. He embodies how even the most disheartened can find purpose and redemption. In a story that celebrates both the shadow and the light of humanity, Hiromi Higuruma stands out profoundly as one of the greatest achievements in character development in Jujutsu Kaisen.$grulla$, $grulla$Higuruma$grulla$),
  ('cmnn874zr000pcnde3vkb53fo', $grulla$We've talked a lot on this channel about how rare it is for a sorcerer in Jujutsu Kaisen to be able to use Reverse Cursed Technique to heal themselves or others. This ability seems to be reserved for the most powerful innate sorcerers, and it's clear how it gives them an edge in combat by letting them push past their limits again and again. However, with the possible exception of Shoko, none of the sorcerers who use Reverse Cursed Technique turn it into the centerpiece of their arsenal, or blend it with their innate cursed technique to make it viable. Or at least that would be the case if we set Iori Hazenoki aside.

Hazenoki isn't a main antagonist in the series; in fact, you could say he's relatively inconsequential and minor. Even so, his technique, and specifically its application alongside Reverse Cursed Technique, is one of the most creative uses of cursed energy we've seen in Jujutsu. This ancient sorcerer was, like many others, reincarnated by Kenjaku into a new body for the Culling Games, where he proved to be quite strong by showing he was on Megumi's level. Unfortunately, both Takaba and Kenjaku demonstrated the gap between their techniques and Hazenoki's, and we weren't able to see much detail about his character. The little we know about him has to do with his personality, which seems to be a product of the era he originally comes from. Hazenoki is one of the most aggressive and brutal sorcerers we've seen in the Culling Games, and he seems to enjoy torturing his opponents. Hazenoki's violent tendencies are both an advantage and a disadvantage, making him incredibly capable of inflicting pain and finishing off his opponents, but at the same time leaving him easily enraged and prone to losing his sanity against an opponent who can exploit his personality.

In terms of power level, Hazenoki's knowledge of jujutsu is quite extensive, and he can easily figure out the abilities of most of his opponents, in addition to being able to mix different techniques into his combat skills. Perhaps his most important trait in a fight is his high tolerance for pain, which allows him to get the most out of his cursed technique. Combined with his sadistic personality and his blinding rage that allows him to kill anyone without thinking twice, this makes him someone quite volatile and dangerous.

As I mentioned at the beginning, Hazenoki is able to use Reverse Cursed Technique, which means he can produce a large amount of positive cursed energy. The understanding required for this energy manipulation is quite deep, which demonstrates his knowledge, and the large amount of cursed energy he can produce allows him to keep fighting long after a normal sorcerer would usually have collapsed from exhaustion.

However, his innate cursed technique, Explosive Flesh, is what sets him apart from other psychopaths in the series. Using this technique, Hazenoki can detonate parts of his own body from a distance and use them as bombs. He normally does this by tearing out his eyes or teeth and using them as explosive projectiles that go off on impact with his opponent. Of course, this is what I meant by the synergy between his Reverse Cursed Technique and his Explosive Flesh, since it allows Hazenoki to instantly regenerate the parts of his body, effectively giving him infinite grenades. Hazenoki's personality and pain tolerance are also quite key to using his technique, since without either of these two, the sorcerer wouldn't be able to overcome the mental barrier of having to tear off a part of his own body in order to use his technique.

Although powerful and consistent, Explosive Flesh doesn't seem to be too devastating, since we've seen multiple people survive its explosions relatively unscathed. And of course, the synergy between his techniques is his greatest weakness, since his Explosive Flesh becomes useless without his Reverse Cursed Technique, which ultimately led to his end at the hands of Kenjaku, who disabled his ability to heal below the neck by attacking his spine.

As you can see, Hazenoki isn't the most complex character in the world. Even so, the creativity and the way he uses his techniques warranted this short discussion about him, since he showed us how a relatively minor character can hold some of the best ideas and concepts of this incredibly versatile power system.$grulla$, $grulla$Hazenoki$grulla$)
) AS v(id, body, title)
WHERE r.id = v.id;
