-- Batch 3: 4 reviews. Run this whole file as one statement.
UPDATE "Review" AS r SET "contentEn" = v.body, "titleEn" = v.title
FROM (VALUES
  ('cmnn878up001jcndex5qmi976', $grulla$In Kimetsu no Yaiba, there are interconnections between all the characters, whether they're protagonists, antagonists, or even side characters, and the beautiful thing about the story is the sense of inherited destiny it conveys through its characters. However, there is one little girl who not only represents everything Kimetsu wants to show us, but who is, all on her own, the most important character in the entire series, not just for the side of the hunters but also for the side of the demons. Of course, she is none other than Nezuko Kamado, Tanjiro's little demon sister.

Nezuko is a crucial character in Kimetsu no Yaiba. Her mere existence is a threat to both humans and demons due to the unpredictability of her demonic powers. Although she has a miraculous control over her bloodlust, many in the Demon Slayer Corps don't believe she should exist. Nonetheless, with Tanjiro's help, Nezuko is allowed to accompany him and others in search of a cure. It's suggested that Nezuko's transition into a demon was never fully completed, hence the room for her to return. Even so, Nezuko's state allows her to transform and gradually evolve, and she does so on several occasions during battles to protect Tanjiro and the rest of her protectors.

As a recipient of the first progenitor's blood, Nezuko was granted demonic powers without remaining permanently in that state. For some inexplicable reason, she developed an unprecedented resistance to human blood and sunlight. However, it seems that most of her resistance comes from her strong sense of protecting Tanjiro. Her brother is mainly there to calm her down whenever she's on the verge of losing control. What we've witnessed since the first season is Nezuko's "dormant" or "hybrid" transformation, where most of her humanity is active. But in the second season, Nezuko finally awakened to her true demonic form, the "Awakened" form. This form is considered the maximum level Nezuko can reach in her demonic powers so far, when she enters an unrestrained state, leaving all of her humanity behind in the process. Her Awakened form is different because the transformation is more complete, making her even more powerful and highly aggressive.

Despite not being a member of the Twelve Kizuki, Nezuko is a very powerful demon. Her most outstanding trait is her extraordinary growth rate, due to the large amount of blood she received from Muzan Kibutsuji when he turned her into a demon. This has been demonstrated in many battles where she was able to defeat her enemies despite being overwhelmed by them at first. She has been shown to defeat her enemies by increasing her own physical capabilities, enhancing her regeneration, or developing her own Blood Demon Art in critical situations.

Nezuko has demonstrated great skill and prowess in combat, surpassing the Temple Demon, the Swamp Demon, and Susamaru. Later on, her power increased even further to the point where she could face members of the Twelve Kizuki, such as Daki, whom she managed to defeat easily despite not initially being a match for her, and Hantengu's clones, with whom she was able to fight on equal terms.

Nezuko has several unique characteristics that set her apart from all other demons. The most notable is that Nezuko can continuously restore her power without consuming human blood, as any other demon would need to do. Instead, she recovers her strength only through sleep, although she would have to spend a long time sleeping in order to recover and regain her power. In addition, Nezuko has an extraordinary growth rate, as has been shown several times when she becomes stronger without any training or consumption of humans. This ability is shown even in the middle of battle and with great increases in power.

Nezuko has the ability to enter a berserker state where she becomes more demonic in appearance, transforming into an adult version of herself with vine-like tattoos surrounding her body and a single horn protruding from the right side of her forehead. Nezuko's physical capabilities in this state increase drastically to the point where she could sever Daki's limbs by stomping on them and kick her from extremely far distances, destroying multiple buildings in the process. Her regenerative abilities also become equal to those of the Upper Ranks of the Twelve Kizuki. When she first awakened this ability in her fight with Daki, she became frenzied in battle, lost her usual restraint toward human blood, and only returned to normal when Tanjiro sang her a lullaby. Over time, she was able to transform into her Advanced Demon Form while maintaining her usual composure and avoiding feeding on or attacking humans.

We can't forget the fact that, like all demons, Nezuko was initially vulnerable to sunlight, and her body would completely disintegrate if exposed to it. As a result, she could only go out at night or in areas with little sunlight. However, in an event that completely changed the order of the war between hunters and demons, during her battle with Hantengu, she suddenly managed to develop immunity to sunlight, which allowed her to be active regardless of whether she was in the sun or not, and earned her the title of "The Chosen Demon."

All of this makes Nezuko completely unique compared to the rest of the demons created by Muzan, and it's what makes her the key piece for ending the series' conflict. However, we can't overlook her special ability.

Blood Demon Art: Exploding Blood

Nezuko's Blood Demon Art allows her to ignite her blood in pink-colored flames at will. Her flames have a special property that makes them harmful only to demons, objects belonging to demons, and the Blood Demon Arts of other demons, while being completely harmless to humans and other objects. These flames can hinder natural demonic regeneration, as was shown when Daki's burns took much longer to heal than traditional wounds. This technique was also able to neutralize Gyutaro's poison to save Inosuke and Tengen. Her flames also have the ability to temporarily turn nichirin swords a glowing red, increasing the strength of the attacks inflicted by them. This technique, mixed with the hunters' breathing styles, can be a weaker replacement for the red nichirin swords needed to finish off the demon king, and it seems specially designed to finish off the kizuki. However, this Blood Demon Art doesn't come without drawbacks, since because Nezuko doesn't consume human blood and depends on the rest of sleep, extended use of her technique causes her to become fatigued quickly, to the point of falling asleep.

In addition to her blood art, Nezuko has shown in her Advanced Demon Form that she has control over the viscosity of her own blood. When her limbs and head were severed and she was about to be attacked by Daki, Nezuko managed to control her limbs and head by coagulating and solidifying the blood gushing from them before the streams could break. She was able to command her limbs to grab and stop Daki's bands, and even though she did so with floating, severed limbs connected by blood, she was able to do it with such force that the bands came to a dead stop. She was then able to bring all her limbs together through those streams of blood, allowing her body to regenerate.

In conclusion, although Nezuko is clearly a relatively weak demon when it comes to the higher tiers of power on the demons' side, her particular abilities make her the key piece for the resolution and evolution not only of the plot but of the main characters on both sides in Kimetsu no Yaiba. Her blood and her very being are both the main motivator for Tanjiro and Muzan and the mechanism by which there exists a hope for stopping the demons, as well as the necessary complement for creating the perfect demon, making her, in my opinion, one of the most interesting characters in the entire work.

Tell me in the comments, which other character would you like to see explained? I'd love to know your opinion. Of course, if you liked this video and want to see others like it, don't hesitate to subscribe, and give the video a like, it helps me a lot to grow the channel.

Now, it's time to take a nap in a comfy dark box, but hey, what do I know, I'm just a crane that comments.$grulla$, $grulla$Nezuko$grulla$),
  ('cmnn878m0001hcndea4cym2ay', $grulla$Action has always been one of my favorite genres (when it's done well). At its best, it's basically a physical form of storytelling, where the climax of a fight reflects the emotional catharsis of the characters. To an outside observer, having a group of people beat each other up might seem simple, but there's an elegant construction behind any great fight scene. For action to be engaging and interesting, you need goals, stakes, obstacles, and twists, as well as characters who are interesting enough and, in the case of anime, good animation.

That said, in this video I want to analyze one particular fight in Hunter x Hunter that I've been thinking about using those elements: specifically, the fight between Netero and Meruem in the Chimera Ants arc.

Hunter x Hunter has always excelled at constructing fights. Between the creativity and the solid foundation of Nen, this anime's version of the typical Shonen superpower, the series demonstrates time and again a great understanding of the crucial elements of a good fight scene that I was talking about earlier. The fight between Netero and Meruem is no exception, as can be seen in its setup. On Netero's side, the goal of the fight is to eliminate Meruem in order to stop the selection process, and the stakes are the survival of humanity itself. The obstacle, of course, is the fact that Meruem turns out to be far stronger than Netero. With just these factors, as an audience, we already have a clear idea of the conflict. However, once the fight "begins," Meruem... decides to sit down and talk with Netero instead of fighting.

It turns out that, on Meruem's side, what he wanted was not to defeat Netero, but to talk with him in order to better understand humanity. His experience with Komugi had made him reflect on humanity's potential, and he wanted to discuss it further. This is a great example of how Hunter x Hunter establishes the divergent motivations of characters in order to alter the dynamics of a conflict. Knowing and understanding why characters fight not only makes the fight emotionally engaging for the audience, but can also alter its trajectory depending on the circumstances, making it more varied and interesting. Now, on Netero's side, we have a twist that prevents him from reaching his goal: his opponent doesn't even want to fight! In better circumstances, Netero might have been willing to indulge Meruem, but here Netero's secondary stakes come into play: if something bad happens during the extermination of the Chimera Ants, the Hunter Association will be held responsible, and that's why Netero is forced to act.

At first, Netero used physical coercion to force Meruem to fight, but Meruem wouldn't budge. As can be seen at this point, the twist in Netero's goal becomes a conflict of its own, with its own set of goals (getting Meruem to fight) and obstacles (Meruem's imposing strength). However, Netero, and by extension Hunter x Hunter, ends up taking advantage of Meruem's internal struggle, that is, his identity crisis, and turns that character conflict into Meruem's goal for this fight. By telling him that he knows his name, Netero manages to force Meruem to fight. And so the battle begins.

Considering that both Meruem and Netero are the strongest characters the series has shown so far, there was some concern about how the fight would play out. Specifically, I was worried that it would all come down to who could hit harder. But this is where Hunter x Hunter once again demonstrates its understanding of goals and obstacles. Instead of simply being "defeat the other," the series chooses to give the fight a very specific condition or goal for winning. The unique nature of Netero's Nen means that, in theory, he has an unlimited number of moves to make, but Meruem takes his time analyzing the patterns of Netero's moves and using those predictions to attack. Thus, the battle between Netero and Meruem becomes a struggle of endurance, where the goal of both sides is the submission of the other. Whether Netero first submits to his own biases, becoming predictable to Meruem, or Meruem gives up before finding an exploitable pattern. Meruem's goal of extracting his name from Netero also acts as a handicap that levels the playing field a little, because it means Meruem can't really go all out against Netero without running the risk of dying, which makes the fight more tense. Once again, this is an example of how the series uses the characters' goals to alter the variables of the conflict. Although it's still clear that Meruem has more advantages, this additional twist makes the conclusion of the fight a little more uncertain.

The Thematic Conclusion

Unfortunately, despite his best effort, Netero ends up losing to Meruem. But this is where the exploration of humanity in this arc of Hunter x Hunter resurfaces, making the conclusion of the fight thematic. Although Meruem praises Netero's strength, he mentions how his power comes from the culmination of the collective instinct of his species, something humanity will never be able to achieve due to the individuality it possesses. But, to Meruem's horror, Netero reveals that the true strength of humanity's individuality does not lie in how our species can surpass itself physically.

Rather, it lies in our capacity to destroy.

In his final moment, Netero detonates the Poor Man's Rose, exploding alongside Meruem. In any other fight, this would be a triumphant moment of humanity's victory, but the following episode reminds us of the grim reality surrounding the bomb. As can be inferred from the shape of its smoke cloud, the Poor Man's Rose is an intentional evocation of the nuclear bomb of our real world. They are both a symbol of humanity's progress and its capacity to fight existential threats, as well as a mark of our own destructive tendencies. Both in the Hunter x Hunter universe and in the real world, these bombs have claimed millions of lives, all dropped by individuals with political motivations for their own ends. And so, once again, we as viewers are reminded of the duality of humanity: our capacity to defeat "evil" and our capacity to harm and destroy.

These elements are why the fight between Netero and Meruem is a testament to what makes Hunter x Hunter a great action series. Not only does it have a strong command of the fundamentals of conflict (goals, stakes, obstacles, twists, etc.), but it also knows how to end its fights in ways that further elaborate on their underlying themes.$grulla$, $grulla$Netero vs Meruem$grulla$),
  ('cmnn878cp001fcndebgobzrpx', $grulla$What is a villain, really? Is it their actions? Their birth? Perhaps their motivations? Is being simply different from humanity a sin that deserves death? Perhaps one of the most interesting characters in Hunter x Hunter is also one of the most dangerous, yet at the same time he is someone who shows more humanity than any of the characters in the series despite not being a human. Meruem is the perfect villain for a series like this one, where morality is a shade of grey, and where even the protagonists who were always good have shown darkness.

Meruem was born a warrior without a heart, respecting people only for their ability to withstand combat with him, but he would eventually become a kind and compassionate pacifist, valuing the time spent with those he cherished even above his own pride. Throughout the Chimera Ant arc, Meruem fought and constantly showed signs of humanity in contrast to his biological birth as a Chimera Ant.

Meruem was born a cruel and violent leader. The Queen's intention to give birth to a perfect offspring was reflected in Meruem's mentality. Inside the womb, he ignored his mother's concern for his development and tore through her abdomen, forcing his own birth. He felt no concern for his dying mother or for the other ants, killing and cannibalizing several Chimera Ants that had decided to tend to the Queen's wounds rather than attend to him. Neferpitou would be the first person to withstand an attack from Meruem, after enduring an attack that Meruem tried to kill her with without defending herself. He showed no empathy toward humans and saw them as nothing more than a source of food, killing and devouring a child shortly after his birth.

Meruem would only begin to change upon meeting perhaps the weakest human of all, Komugi, which later evolved into a deep affection for her. With this change of heart, Meruem began to question the differences between the Ants and humanity, and he struggled with his identity as half human and half insect, questioning the nature of violence and strength as true power. After his interactions with Komugi and his fight against Netero, Meruem began to see humans as incredible beings with immense potential through their tenacity to surpass their own limits. He showed great respect and complete admiration for Netero, seeing his abilities and fighting style as truly magnificent, and he constantly praised him during their battle, referring to him as a rare example of a human who has transcended his limitations and reached the pinnacle of human capabilities. Because of this change of perspective, Meruem no longer considered farming humans for food and instead suggested the coexistence of humans and Ants, with humans being selected and controlled by their quality.

The traits that define Meruem are his pride and his self-confidence. From his birth to his death, Meruem displayed a strong confidence in himself and conviction in his actions. He insisted on proving his intellectual capabilities to himself by defeating the champions of various board games at their own games shortly after learning their rules. However, after losing several games against Komugi, he showed his first sign of human emotion, trying to scare and distract her during a game of Gungi by threatening to tear off her arm if she lost. Komugi managed to exceed his expectations and responded with such respect toward him and the game that Meruem tore off his own arm in apology for his insolence and disrespect toward her and the game.

He considered certain concepts of human society to be absurd. Examples of this were when Shaiapouf explained how certain people could become rulers through connections or lineage rather than power, something Meruem saw as a contradiction to all natural logic. When he understood the injustice of human society, where children starve to death while the pathetic weak have everything they need, he wanted to destroy this madness and create a new world where the concept of inequality would be completely forgotten. Furthermore, he came to believe that the true purpose of power is to protect the weak who deserve to live, not to torment the defeated.

He was highly skilled and learned things at an astonishing rate, being able to master any form of board game in only ten matches and defeat world champions with ease. After a brief loss of memory, he seemed to become much more respectful and close to his subordinates after having been fed a part of them when he was dying, as he could feel what they felt and easily tell whether or not they were hiding something from him; at the same time, he could perceive their loyalty toward him, which led him to test their loyalty before considering punishing them, all the more so if they answered with the truth despite doing so meaning admitting a miscalculation. The sense of loyalty he felt from them was so strong that it prevented Meruem from killing both Pouf and Youpi for lying to him, despite having previously told them not to lie to him.

Despite his extreme arrogance and superiority complex, he felt fear for the first time when Netero prepared to detonate the Poor Man's Rose and unleashed an incredibly malevolent aura and supreme confidence despite being on the brink of death. Moments before succumbing to the poison, he admitted to Palm Siberia that humanity had won and was willing to accept his defeat. His desire to fulfill his last wish was so strong that he was willing to kneel before her.

In terms of power level, despite being a newborn, Meruem is the most powerful character introduced in the series so far, as well as the one possessing the greatest learning capacity. Born as the ultimate biological weapon, his tremendous physical prowess is matched only by an incomparable intellect, both of which seem to place him far beyond the realm of human possibility. As the King of the Chimera Ants, his power surpasses even that of the Royal Guards, and he can increase it further by consuming Nen users. He fought Isaac Netero, who was previously considered the strongest Nen user in the world and who maintained a formidable power level even in his old age, while trying not to kill him, a condition Meruem compared to playing chess without a rook or a bishop, and he won their physical confrontation. After absorbing most of the bodies of Shaiapouf and Menthuthuyoupi, Knuckle believed that state-level military power would be necessary to match him. As king of a Chimera Ant colony, Meruem has authority over the Royal Guards and the ability to procreate with females of different species.

As soon as he was born, Meruem already possessed enough strength to blow off the heads of several Squadron Leaders with a single strike of his tail in each case, as well as to pierce a hole in the nest with such force that the entire structure shook. By driving his tail into the outer wall of the nest, he was able to launch himself high into the air. His tail is so powerful that it allowed him to wound all three Royal Guards, though only slightly, although he failed to kill Neferpitou and held back on at least one other occasion. He was able to effortlessly cut off Netero's left arm and right leg, as well as, even more remarkably, his own left arm, despite the outstanding durability of his body. With the help of Ren, he managed to push back two of the hands of Netero's 100-Type Guanyin Bodhisattva.

Meruem could move so quickly that, a few moments after his birth, he decapitated two Squadron Leaders without them or Colt managing to see him move. The Royal Guards also did not seem able to react. In the brief instant when Netero and Zeno were distracted by Neferpitou's aura, Meruem managed to calmly walk between them without being detected. By his own admission, the only time Netero's speed surpassed his was during the movements of Netero's hands when activating the 100-Type Guanyin Bodhisattva. In the final part of their duel, with both fighters' senses at their peak, they exchanged more than a thousand blows in less than a minute: at the very least, this means that Meruem regained his balance after being pushed by Netero and launched a new offensive more than 16 times per second. However, Netero's hand movements were so fast that Meruem could not see his first attack, and only thanks to the psychological phenomenon known as Spirit Echoes did he barely manage to keep pace, until he finally managed to dodge a flawed counterattack. After absorbing Menthuthuyoupi and Shaiapouf, he became so fast that he reached and knocked out Meleoron and Knuckle immediately after their En registered him, giving them the impression that he had teleported, and he knocked them out without either of them being able to react. He also acquired the ability to fly, which increased his already supersonic speed to the point that Shaiapouf believed it had quadrupled.

Thanks to his astonishing memory and analytical skills, Meruem mastered multiple board games just by reading the rulebooks and defeated three national champions in only a few matches, a time that decreased as he learned more games. He is able to examine multiple scenarios in a matter of seconds. He excels at identifying his opponent's "rhythm," the unconscious bias that guides their choices, and at disrupting it or using it against them, not only gaining information about their thought process but also managing to exploit it in his favor. Playing Gungi with Komugi elevated his pattern-recognition skills to an ability akin to precognition. Thanks to this faculty, he was able to penetrate Netero's otherwise impenetrable defense, even predicting in advance which parts of the body he could cut.

As far as his Nen is concerned, Meruem is an Emitter. He was born with the ability to use Nen and with an enormously superhuman amount of aura, which surpassed even that of the Royal Guards. By feeding on Nen users, he further increased the size of his aura. After consuming Shaiapouf and Menthuthuyoupi, his aura reserves and production became so vast that even the overprotective Royal Guards had to admit that the King seemed invincible and capable of winning a Nen battle through the sheer quantity of his aura alone. Upon sensing his Ren, the members of the Extermination Team despaired, with Knuckle believing that they would need the military power of an entire country to defeat the King.

He was able to perform Gyo shortly after his birth without receiving any instruction. His Ren instilled fear even into Netero's heart, and it allowed Meruem to open the hands of the 100-Type Guanyin Bodhisattva, as well as to emerge completely unharmed from the Third Arm, whereas Netero's First Arm had previously made him spit blood. This defensive application of Ren may imply that he is capable of using Ken.

The first time he used En, it covered an area far larger than the palace grounds and expanded at the speed of light. Despite its vastness, his control over it is so refined that he was able to discern changes in the environment as small as fresh footprints. At first, without his knowing it, his En transmuted part of his aura into photons that transmitted information to him. When, after only two uses, he realized this characteristic of his En, he was able to turn it into a Nen ability. The absorption of Shaiapouf and Menthuthuyoupi granted him variations of their Nen abilities, which he was able to activate successfully on the first attempt.

These are some of his Nen abilities.

Aura Synthesis

Meruem's initial ability grants him strength through consumption. His aura grows each time he devours a Nen user, as their aura is synthesized with Meruem's. The amount of the body he needs to consume to achieve this is unknown, but it seems that Meruem must absorb most of their body in order to use his ability. Neferpitou suggested that this is a Nen ability rather than (merely) a biological one.

Metamorphosis

After absorbing large parts of Shaiapouf and Menthuthuyoupi, Meruem is able to use Menthuthuyoupi's ability to transform, including the ability to generate wings to fly. This allows him to fly at such high speed that he was able to cover a distance that Menthuthuyoupi and Shaiapouf estimated would take 15 minutes in only 5 minutes.

Outburst of Rage

After absorbing large parts of Shaiapouf and Menthuthuyoupi, Meruem acquired the ability to fire explosive bursts of aura from his arm. A single burst has enough power to severely damage a large rock formation.

Photon:

By combining the abilities inherited from Shaiapouf with his own En, Meruem created his own version of Spiritual Message. It consists of converting his aura into microscopic photon-like particles and deploying them with his En in an instant, or of detaching the photons from his body and scattering them into the surrounding air. Each photon retains its aura even when separated from Meruem's body. This ability allows him to measure the shape, quality, emotion, and other informational content of the things the photons interact with; therefore, this ability likely also involves Emission and Manipulation. According to Welfin and Shaiapouf, Meruem can detect everything, even lies. The accuracy of the information he can gather depends on the number of photons directed at the object of interest. It is also briefly shown that, immediately after deploying the photons in a flash, Meruem appears to teleport to the immediate vicinity of any target of interest within the affected region. However, it is unclear whether this is actually part of this ability or whether Meruem is simply covering extraordinary distances instantly with his immense speed.

It is clear that the interesting part of Meruem's character is his evolution into becoming human and his contrast with the so-called humans of the arc. This, and his relationship with Komugi, overshadow the specific abilities of the king of the ants, and that is why almost no one is able to tell you what his specific abilities are, with the exception that he is the strongest of all. Characters like Meruem are seen very rarely in anime, and I would dare to say that his execution is what makes this arc as valued as it is.$grulla$, $grulla$Meruem$grulla$),
  ('cmnn8783x001dcnde3rrf23oc', $grulla$One of the most interesting aspects of Jujutsu Kaisen is its Heavenly Restrictions. These particular traits of certain characters are so striking that they manifest in every aspect of their techniques and even in their personalities themselves. We have seen several examples where such restrictions partially or absolutely strip characters of their cursed energy and replace it with physical abilities and superhuman perception; however, there is only one example of the opposite, a Heavenly Restriction that leaves the person completely physically invalid and, as a consequence, grants them an absurd reserve of cursed energy and the ability to store it indefinitely. Of course, the character with this terrible restriction is Mechamaru.

Kokichi Muta, also known as Mechamaru, is a second-year student at the Kyoto Jujutsu School and one of the key characters in the development of Jujutsu Kaisen's plot. As we mentioned before, he was born with a fragile and weak body due to his Heavenly Restriction, and in exchange his reserve of cursed energy is absurdly large.

Sadly, as a result, Kokichi was unable to attend the Jujutsu School in his human form, but instead used a substitute known as Ultimate Mechamaru, a cursed corpse-like robot controlled by his Puppet Manipulation technique, which he can command at will.

Kokichi is initially shown with wrinkled skin and covered in bandages, lying in a bathtub with tubes around him keeping him alive. He is missing his right arm and has no sensation below the waist. In addition, he has extremely sensitive skin that cannot be exposed to outside air. In exchange for this, Kokichi has a vast amount of stored cursed energy and primarily uses his Puppet Manipulation technique to control Mechamaru and his other puppets. Kokichi is for the most part a calm character who hates having been born and would do anything to lead a normal human life. He compares himself to Panda, who is also a cursed corpse like Mechamaru, which enrages him, as he is jealous that Panda can explore the world while he is trapped inside Mechamaru's consciousness.

Kokichi simply wanted to live a normal life with his classmates as an ordinary human jujutsu sorcerer. Later, it becomes clear that his desperation knew no bounds, as he ends up betraying his friends by making a binding vow with Mahito and Kenjaku to provide vital information in exchange for a healthy body. However, he asks them not to harm his friends, but as soon as the binding vow was completed, a battle with Mahito breaks out. Kokichi, realizing that he needs to protect his classmates, plunges into an all-out battle with Mahito, during which he excellently showed us the levels he was able to reach with his cursed technique, tactical intelligence, mechatronic skill, and reserve of cursed energy.

Innate Cursed Technique: Puppet Manipulation

Kokichi's technique allowed him to remotely control puppets or cursed corpses across a wide range. Puppets such as Mechamaru are capable of using cursed energy discharge as heat rays, among a variety of other abilities.

Having been paralyzed for most of his life, Kokichi transferred his consciousness into Mechamaru's mechanical body, which gave him the ability to move, interact with his colleagues, and also granted him combat abilities. Despite his physical limitations, Kokichi was able to fight effectively against curses and curse users by using Mechamaru to his advantage. Equipped with devices and weapons that enhance Kokichi's jujutsu abilities, Mechamaru was capable of firing cursed energy in the form of high-intensity beams from his palms, transforming his arms into deadly weapons and powerful shields.

Thanks to Kokichi's Puppet Manipulation technique, he was able to control multiple Mechamarus wherever they were. Mechamaru also has an even more powerful move known as Mode: Albatross, which allows him to reveal a cannon inside his robotic mouth capable of firing an immense beam of cursed energy from the barrel, destroying everything in its path.

During Kokichi's final battle, he used Ultimate Mechamaru-Mode: Absolute, a gigantic mechanical puppet that Kokichi can control from the cockpit located in its head. Of course, we fans know that the abilities and combat style of this version of Mechamaru are a subtle nod by Gege to the legendary Evangelion.

The gigantic mechanical puppet also had its own set of powerful attacks, such as the Miracle Cannon, a powerful burst of energy from both hands, and the Dove Viola, the cursed energy version of guided missiles, which follow targets until impact. Kokichi's Heavenly Restriction also plays a key role here, as he was able to gather a vast amount of cursed energy consisting of seventeen years, five months, and six days of cursed energy accumulated throughout his life, allowing him to unleash powerful attacks all at once.

As for barrier techniques, Kokichi was able to develop a technique known as the New Shadow Style: Simple Domain. He executes this by firing a sharp bullet from the giant puppet's finger; once the bullet enters the opponent's body, Kokichi can activate his Simple Domain cursed technique.

Kokichi is also known for being a great strategist who can assess his opponent and take advantage of his surroundings; even Kenjaku praised him for his tactical intellect during his fight with Mahito. Kokichi continually came close to defeating Mahito and damaging his body.

During the Shibuya Incident, although dead, Kokichi appears in the form of a small circular mechanical device, consisting of the final remnants of his cursed energy. He used his remaining cursed energy to help his classmates navigate the surrounding dangers and also supported them during their battles against the enemies.

We have seen few intellects like Kokichi's, and even though he is no longer with us, we can praise his character as one of the most important supporting characters in all of Jujutsu Kaisen, giving him the spotlight during much of the Shibuya Incident arc, vindicating him in the minds of many and raising him up the ranks of the fans' favorite characters.$grulla$, $grulla$Mechamaru$grulla$)
) AS v(id, body, title)
WHERE r.id = v.id;
