-- Batch 1: 4 reviews. Run this whole file as one statement.
UPDATE "Review" AS r SET "contentEn" = v.body, "titleEn" = v.title
FROM (VALUES
  ('cmnn87aur001zcnded94p6yju', $grulla$In the real world as much as in anime and manga, everything is about balance. Sometimes, when you have impulsive and relentless characters, you also need a shy and cautious one in order to show the audience both sides of the coin and make the story feel more real. Likewise, these shy characters who think before they act generally offer the best opportunities for development, allowing them, through effort and motivation, to break out of those birdcages in which they encase themselves and to reach new heights. In Hunter X Hunter the best example of this is Shoot, who, despite being overshadowed by the rest of the characters in the Chimera Ant arc, is probably one of the most developed characters, and has one of the most interesting abilities of the arc.

Shoot has a shy personality and is often afraid to seize the opportune moments to attack an enemy. His prudence makes him a good contrast to Knuckle, since he counters the latter's impulsiveness with his colder and more analytical mind. He was willing to let thousands of people die for the sake of saving billions of others, showing himself to be someone Machiavellian. However, when the fight with Youpi begins, he is inspired by Gon and is able to unleash his full power, overcoming his shyness and his wounds.

We tend to think of Hunters as people who love to fight in order to achieve their goals; however, Shoot is a great example of the opposite. He is someone who, by his own confession, does not like to hurt others, not even if they deserve it, and fears for his own well-being more than most of his companions. This can make him feel like someone hesitant, and maybe he is, but it is his ability to overcome this and give everything of himself to protect his companions despite not having this tendency naturally that makes him so inspiring.

In terms of power level, Shoot has demonstrated remarkable combat prowess by briefly facing Youpi, a Royal Guard, on his own, although he suffered nearly fatal wounds. Additionally, with Knuckle's help, he was able to seal the manipulated body of Kite, who was fighting without restrictions of any kind, an extremely notable achievement. His low confidence in his abilities has often been an obstacle for him, but Gon's example allowed him to discover his own determination, which enabled him to attack Youpi without worrying about his own life. He is very observant, noticing Killua's electric attack before he could carry it out. His Nen abilities allow him to effectively compensate for the loss of his left arm.

Perhaps Shoot's most important physical attribute is his speed, since he can move so quickly that the slightest distraction from Killua allowed him to close the distance between them before the young Hunter could react, although he managed to avoid the subsequent blows when he was not under the effects of his brother's conditioning. Shoot noticed electricity around Killua's hands and withdrew before Killua's ability could connect. While flying on his hand, he becomes extremely fast, dodging and redirecting many of Youpi's attacks despite their number, and even managed to touch the Royal Guard's body once.

Some of Shoot's most overlooked abilities are his spatial reasoning and balance, both key to being able to use his ability at the level he uses it, and despite being someone who does not like to fight and fears getting hurt, his stamina and resistance to pain are remarkable, being able to keep fighting after Youpi's attacks to his leg and after suffering lethal wounds all over his body.

Finally, Shoot is one of the most expert Hunters in pursuit and hunting, being able to follow his prey's tracks expertly and better than most other Hunters.

When it comes to his Nen, Shoot is a Manipulator*. He specializes in manipulating three hands that he uses as controllable projectiles or as distractions to land a blow and activate Hotel Rafflesia. The repeated disappearances and reappearances of his birdcage, and especially of the hands, seem to suggest that they are conjured. Since he does not like to hurt others, Shoot made his main Nen ability one that can only be used by injuring someone, so he would resort to it when he had no other option and, therefore, would have no qualms about using it. Another of his abilities allows him to convert small objects into two-dimensional impressions in his right hand. He is an extremely capable user of Zetsu who went unnoticed by Gon and Killua for nearly a month. He also appears to be competent in Shu, since he is able to imbue his floating hands with aura. During the attack on the Chimera Ants, following a hunch, Shoot covered his right eye, which, together with the thrill of feeling cornered, increased his strength, indicating that he is potentially a user of Nen restrictions.

Going into more detail on his Hatsu, which can be a little confusing to understand, Shoot calls it Impression Conversion, which uses his Nen to convert pocket-sized three-dimensional objects into impressions on the palm of his hand, as well as returning them to their normal state without damage. It seems that Shoot can maintain the effect for at least several days. This allows him to use two sub-techniques, the first of these, and the one we most often see him use, being the floating hands.

Shoot can conjure three floating hands, which he then controls with Manipulation. He can coat them with aura and use them as projectiles capable of surrounding and striking the target, but also as distractions to get close to the opponent and activate Hotel Rafflesia. Shoot has great control over the hands, which he can position to exploit the blind spots created by Hotel Rafflesia. The aura around a single hand allows him to have enough power to damage Killua, though not enough to hurt him significantly, as well as to come out unharmed from Killua's attacks, both physical and through his yo-yos. During the fight against Youpi, Shoot was able to control the hands with such precision, speed and power that they were able to defend against the Royal Guard's tentacles. He could also stand on one of them to fly quickly, which he considers his special technique. Despite the fact that Shoot always uses the hands together with the cage of Hotel Rafflesia, the two abilities seem distinct.

But now that I mention it, what is Hotel Rafflesia?

This second ability allows him, through physical contact, to steal specific parts of the opponent's body through physical contact, shrinking them and teleporting them to his birdcage, potentially until their entire body is sealed. The affected body part is replaced by a dark mist. Although the opponent feels no pain and is not actually injured, Shoot's ability can throw their mind into chaos. Furthermore, by targeting the eyes, Shoot can create blind spots to exploit in successive attacks. To deactivate the ability, Shoot opens the door of the cage, allowing the trapped target to walk out, after which they return to their normal size. It deactivates automatically if Shoot loses consciousness. Given that the size reduction is associated with Conjuration, it seems that Hotel Rafflesia also incorporates elements of this type of Nen. Its teleportation component may mean the additional involvement of Emission.

Shoot's abilities are interesting because, in addition to being useful in situations that are not only combat but also support, they are abilities that contrast greatly with his personality, which is completely intentional. You see, Shoot is one of the few characters in Hunter x Hunter who knows his flaws and limitations perfectly, and he uses his technique as a way to force himself to set aside his shyness and to hurt others. This technique, which requires stealing others' bodies from them and striking them from multiple directions, is as much a torture for his opponents as for himself, and only after Gon's help and inspiration did he finally manage to reach his potential.

Sometimes you hear criticism of Shoot for his indecision, shyness and cowardice. But these critics do not stop to think about the effects that these qualities have in an arc where most of the characters are overly impulsive and decisive, and who, if they would only stop to think for a second, could obtain a better result. This, added to his rapid development and the lesson his character teaches the audience, makes him someone worthy of participating in this incredible arc and of being regarded as an essential character for this wonderful Shonen.$grulla$, $grulla$Shoot$grulla$),
  ('cmnn87als001xcndedn08xqae', $grulla$The ability to heal with the Reverse Cursed Technique is extremely rare and coveted in the world of Jujutsu Kaisen. The control required to perform it, along with how difficult it is to explain how to achieve it, makes it one of the hardest abilities to master, and only a handful of sorcerers are capable of using it at will. What's interesting is that you don't need to be a genius on Yuta's level to pull it off, and we even have a relatively low-ranked sorcerer who is a specialist in this technique. Of course, I'm talking about Shoko Ieiri, the complement to Geto and Gojo's group at the Tokyo Jujutsu school, and who is currently the academy's healer.

Shoko is a very relaxed and carefree person, especially compared to Ijichi's nervous attitude and Gojo's excessively playful one. As a student alongside Gojo and Geto, she lets the two of them fight and simply removes herself from the situation while calmly climbing the ranks at school. This makes her the perfect complement to these two special grade sorcerers, since she is content to just work behind the scenes and stay out of their way.

Shoko doesn't seem to take any situation very seriously in general during her years at the Jujutsu Academy. She openly smokes in public despite obviously being a high school student, and this habit stayed with her into adulthood. Even after Geto betrayed them, Shoko was able to have a casual conversation with him about what he did. She feels completely comfortable asking him about the accusations and even called him childish for being in a bad mood because no one understands him. She even called Gojo to come confront Geto right in front of him without any fear for her own life.

As the school doctor, Shoko seems to take her job seriously and acts in a very stoic manner. While Gojo was visibly upset over Yuji's death, Shoko kept her personal feelings out of the situation and just wanted to perform an autopsy, pointing out that Gojo was being more emotional than usual. It's hinted that Shoko has tried to quit her smoking habit many times, but the stress of her work as a healer probably makes it harder. She stated that she was "nostalgic for her high school days" when she was noticed smoking again in Shibuya, showing that she still thinks about and cares about what happens to her former classmates and the new students.

As one of the few healers at the Jujutsu Academy and a user of the Reverse Cursed Technique, Shoko is a valuable asset to her colleagues and students alike, and she has saved many sorcerers even on the brink of death. She stays composed on the battlefield and doesn't worry about being discovered in Shibuya despite the danger of being a high-value target.

In terms of power level, it's clear that Shoko is not the combat type of sorcerer, but she still participates in missions with Gojo and Geto while training as a student, which indicates she possesses some kind of combat abilities. Shoko doesn't show the ability to use normal cursed techniques, but she clearly possesses the rare ability to use the Reverse Cursed Technique. She can apply it to others to regenerate lost limbs and heal wounds, something not even Gojo can do. However, when asked how it works, Shoko can't put it into words that could effectively teach someone else how to use it. This shows that she uses it instinctively and doesn't really understand it, which limits its effectiveness.

Shoko possesses the necessary knowledge of a traditional doctor and also has the skills to save her comrades at any given moment. She is invaluable to the sorcerers of the Jujutsu Academy as the only healer of this kind besides Yuta, who is more valuable in combat. When Nanami is injured by Mahito in their first fight, he retreats to the Academy to receive treatment from Shoko. Ijichi and Ino would have died if they weren't treated immediately by her during the Shibuya Incident as well.

Her skills as a doctor also make Shoko very knowledgeable in the field of sorcery in relation to biology. When dissecting two transfigured humans, Shoko is the one who is able to discover that they aren't actually cursed spirits but humans transfigured by a cursed technique. Shoko is also the one who correctly theorizes that the Culling Game's cursed technique removal penalty will affect the players' brains and end their lives as a result.

Even though Shoko doesn't know how to explain it properly, there is a very clear idea of how the Reverse Cursed Technique works.

Basically, this technique processes negative energy into positive energy by taking two sources of cursed energy and multiplying them together. As a result, the energy that destroys becomes energy that creates, and negative energy becomes positive. Despite sounding simple enough, producing positive energy is extremely complex and difficult for most jujutsu users to perform.

Positive energy can be used for various purposes, but most commonly for healing. Cursed energy comes from negative emotions, which are not suitable for healing living beings. However, cursed spirits, which are made up of cursed energy, don't require the Reverse Cursed Technique to heal. Jujutsu sorcerers mainly use positive energy to generate new flesh and heal human bodies. However, even using the Reverse Cursed Technique to heal wounds can sometimes leave a scar. While very few sorcerers can use the Reverse Cursed Technique, there are even fewer who emit it to heal people other than themselves, like Shoko. However, when used to heal others, the Reverse Cursed Technique is less than half as efficient as when healing oneself.

The Reverse Cursed Technique can even be used to replenish a depleted cursed technique after using a Domain Expansion. However, one cannot heal their body at the same time as their cursed technique, and this is something too advanced for Shoko, something we've only seen in the most powerful sorcerers.

The Reverse Cursed Technique can also be used to heal wounds on the soul; however, this requires the user to be able to perceive the shape of the soul, something that Shoko unfortunately is incapable of.

In conclusion, Shoko isn't really the strongest character, not even within her own specialty. However, the special thing is that her ability to use the Reverse Cursed Technique to heal others makes her invaluable to the Jujutsu sorcerers, and someone without whom not only our protagonist but a large part of the cast would have ceased to exist. So we should give this behind-the-scenes support character her due, and maybe understand her and let her smoke a cigarette every now and then to relax.$grulla$, $grulla$Shoko$grulla$),
  ('cmnn87ad0001vcndex5ed0jav', $grulla$The world of the Yokai in Dandadan is one of sadness, tragedy, and horror. These Japanese monsters seem to exist to torment the living in different ways, whether those who interfere with their territory, or those who, for one reason or another, catch their attention. However, we have seen how the Yokai are not necessarily evil, but rather peculiar when it comes to their moral code and their decisions, acting in emotional and not very logical ways, yet with reasons that are not entirely far-fetched. In particular, those Yokai who were born from the strong emotions of living people seem to have unique and specific goals, which makes them easier to understand. We have already seen several Yokai with different motivations and personalities, but I think there is no better example of a Yokai with clear motivations than Acrobatic Silky, or Akusara, the Yokai who lends her powers to Aira.

When she was alive, Acrobatic Silky was a woman in debt who had to work multiple jobs, including serving as a prostitute, working as a janitor, and as a cashier at a store, all while caring for her only daughter, whom she loved deeply. After deciding to use part of the money she earned to buy her daughter a dress, the men to whom she owed money came to her house to collect what she had, beat her brutally, and kidnapped her daughter. The mother desperately chased the van in which the men took her daughter away, but it was in vain, as she fell to the ground and watched helplessly as the van disappeared from her sight. In her despair, combined with the knowledge that she would never see her daughter again, the mother performed one last dance on the rooftop before throwing herself into the void, with her final thoughts focused on her daughter.

The woman's spirit wandered through the city for an unknown amount of time and lost the memories of when she was alive as she became a Yokai, although she felt that she had lost something very important. While she was in the streets, a little girl named Aira Shiratori approached her after mistaking her for her deceased mother, but left with her father upon realizing her mistake. This misunderstanding led the woman to believe that in her previous life she had been Aira's mother, developing an obsession with protecting her. This obsession transformed her into the Yokai we call Acrobatic Silky or Acrosara. She spent the following ten years stalking Aira until she could finally see her again and call her "mother."

Akusara took the form of an extremely tall woman with gray skin, long limbs, and long, silky, jet-black hair. She had a narrow face with sunken eyes, wrinkles on the upper part of her face, and a permanent smile painted with lipstick that exposed her large teeth. She wore red polish on her fingernails and toenails, with long nails on her hands. She walked barefoot while wearing a red wide-brimmed hat and a red dress (similar to the one she had bought for her daughter), with a violet collar that accentuated her long neck. At first, her face looked as it did in life, until the day she met Aira and transformed into a complete Yokai.

Due to her tragic past, in which her daughter was taken from her, Acrosara is a yokai with a desperate need to find a child to love and who would call her "mother." Her main fixation is Aira, after becoming delusional in believing that she had been her mother in life, which led her to obsess over the idea of having her all to herself. Her intentions were also driven by her maternal instincts, as she was willing to sacrifice her own aura to revive Aira, and even tore off her own jaw to assure Momo that she would not try to eat her.

Of course, as her name indicates, both the original human and the Yokai have considerable confidence in their acrobatic and ballet abilities, using these movements as their main martial art. Her exceptional speed, agility, and reflexes allow her to react in time and dodge a fast charging attack from Okarun, who uses Turbo Granny's speed.

In addition, her leg strength is incredible, easily able to send humans flying with a simple kick and able to break free from Momo's psychic force.

Her endurance is a point we cannot overlook either, as she has shown us that she is resilient enough to get back on her feet after taking damage from Okarun's strongest blow and being sent flying through a building.

The main advantage of Akusara's special ability is that it allows her to extend her hair to considerable lengths and manipulate it at will. Her hair can entangle anything in her surroundings, which allows her to capture and throw her opponents. In addition, it helps her traverse difficult terrain at extremely high speeds.

A significant vulnerability of Akusara's acrobatic abilities is her susceptibility to fire, as this could scorch her hair, hindering the process of untangling the objects to which it is attached.

Together with her acrobatic movements, Akusara uses her hair to entangle her surroundings. This allows her to immobilize her enemies, trap them, and even strike them by using her hair against other objects. Her hair can also act as additional limbs, allowing her to grab objects from her surroundings to use as weapons. Her hair is so long and flexible that it can be used as traps, to hinder the movement of her enemies in enclosed spaces.

The inspirations behind this Yokai are quite interesting, as they seem to mix legends from two distinct cultures. Akusara's abilities and appearance are directly inspired by the Japanese urban legend of the same name, about a mysterious entity that resembles a tall and slender woman, with pale skin, dressed in an elegant red dress and a matching wide-brimmed hat. Her long, silky black hair and her unsettling presence make her unforgettable. She is frequently seen in large cities performing dangerous acts, such as dancing atop buildings, moving erratically across distant rooftops, and leaping from them like an acrobat.

After her performance, the spirit vanishes without a trace, leaving onlookers bewildered and terrified. According to the legend, those who witness Akusara's acrobatics are cursed, doomed to experience misfortune or even death.

However, her personality and story more closely resemble the Mexican legend of La Llorona, or the woman who weeps profusely for her lost daughter and is cursed to wander in search of her for all eternity.

This Yokai may be the most interesting in terms of her story, as we see it in its entirety and it allows us to understand that there is more to these Japanese monsters than meets the eye. Additionally, her relationship with Aira is the deepest and friendliest of all the possessed humans, which makes her a character easier to empathize with than Turbo Granny or Evil Eye. Of course, her inspirations are as clear and interesting as those of the other Yokai, but it is impressive how much attention has been paid to a character who is relatively secondary as far as the overall story is concerned, and once again it demonstrates the hidden genius of Dandadan.$grulla$, $grulla$Acrobatic Silky$grulla$),
  ('cmnn87a3h001tcndeqowwdljm', $grulla$Throughout the journey of One Piece, many stories are told that make us think from the deepest part of our being, and even cause us to reevaluate ourselves on a personal level. But in my opinion, of everything that has been told in the anime so far, no story comes close to the impact of the evolution of our favorite Straw Hat chef, Black Leg Sanji.

Not everything about Sanji's character is perfect. Oda has given him certain personality traits that neither I nor many fans agree with, particularly his unbridled perversion, which at times even contradicts a part of his personality, the kind of knight in shining armor he is with women. However, I would venture to say that this is not his main struggle in psychological terms, but rather an entirely secondary one. Sanji's central struggle is even more fundamental, and it is rooted in the nature of his family and his childhood: what do you do when everyone around you is inhuman and you are the only human with emotions? And what would happen if, over time, you saw the possibility of becoming someone inhuman yourself, and how would you deal with that?

Sanji is one of the characters who has received the most flashbacks in the work, not only with his original story alongside Zeff, surviving on the island with no food, but also with the entire story of Germa and of his family as the children of the mad scientist Judge. To recall the context: Germa 66 is a group of villains who literally stepped out of a cartoon, using technology to clone superhumans and create cyborg children with superhuman abilities and no emotions. Judge managed to turn Germa into the largest group of military mercenaries in the world of One Piece, single-handedly winning countless wars in the North Blue. All of Judge's children, from Yonji on down, are superhumans capable of doing anything, since they lack any kind of empathy. Well, perhaps there is one small exception. But do you know who is not just an exception, but someone who goes completely against everything that Ichiji, Yonji, and even Judge himself represent? Sanji.

Sanji, the third son of Judge and Sora, was born without the superhuman abilities of his brothers, and on top of that, he was born the most human of the entire family, having empathy even for the smallest animals. He grew up watching how the normal thing around him was to be useless for not being like his brothers, yet somehow instinctively understanding the difference between good and evil, and deciding for himself, despite all the influence of his father and his own brothers, to do good. A large part of this came from the influence of his mother, who, despite being with Judge, also seems to be an empathetic and sensitive person, and who surely taught Sanji the difference between what the rest of his family does and the broader morality of the world he lives in.

That is surely the origin of two key aspects of Sanji. One: his absolute empathy, being the only ray of sunlight in a world as dark and devastating as Germa. And two: his unconditional love and devotion to women, since the female gender was the only one that showed him appreciation and taught him that he was not completely useless. The love given to him by his mother Sora and by his sister Reiju at different moments in his life taught him that women are to be admired and protected, and that under no circumstances should he attack them or fight against them.

Sanji grew up seeing the rest of his family as inhuman monsters who tortured everyone around them, even him, for lacking the abilities and mindset of his brothers. To Judge, Sanji is trash, and to Sanji, Judge and his experiments are subhuman, complete demons. This defines his character as someone who not only seeks humanity through his demonstrated empathy, shown when he grows up by his complete objectivity in everything that involves feeding someone, no matter whether they are good or evil, but who also seeks humanity as an absolute rejection of his birth family, going so far as to discard the Vinsmoke surname and to consider his adoptive father his only family. In the area where Sanji shows his love, the kitchen, Zeff was not just someone who taught him to cook, but an adoptive father who reinforced the main characteristics that Sanji demonstrates throughout the story: loyalty, empathy, calm, and chivalry. I think it is fair to say that without Zeff's influence, Sanji probably would not be the person he is today.

Throughout One Piece, Sanji has demonstrated a capacity to observe situations and to act in an intelligent and measured way in order to gain information or save his friends. Two perfect examples of this are when he had the conversation with Crocodile, extracting information from him, and when he infiltrated the train on the way to Enies Lobby, predicting that something was wrong with Robin. But it is only in the second part of the story, after the time skip, after Marineford, that we see the true depth of Sanji's humanity, and how at times he wavered between having to adopt his inhuman side, granted to him at birth by Judge's experiments. Specifically, the Whole Cake Island and Wano arcs show us this.

In Whole Cake, Sanji finds himself in a contradiction of his principles. On one hand, abandoning the Straw Hats, marrying Big Mom's daughter Pudding, and returning in a certain way to the wars of his family is the only way he sees to save the most important people in his life, giving himself up completely and selflessly. But on the other hand, this forces him to act like an inhuman being who does not think about the real feelings of his captain and his nakama. Nothing demonstrates this better than the fight between Sanji and Luffy, where Sanji shows his conviction to the point of attacking Luffy with all his strength to force him to stop chasing him, begging him in order to save him. This stubbornness is a demonstration of Sanji's distrust in the abilities of Luffy and the rest to find an alternative to solve the current problem, and it contradicts Sanji's apparent inhumanity with his real, human intentions. It is only when Pudding reveals her true self and Sanji's heart is completely broken, and faced with the complete confidence in Sanji's humanity that his captain Luffy holds despite the beating Sanji gave him, that he finally makes the decision to reject the path painted for him by his family and chooses to leave with his new family, his Straw Hats.

However, even after Whole Cake Island, there are residues of Germa's influence in Sanji's mind, and there is no better reminder of this than his Raid Suit, a tool of war created by Germa specifically for him, which ironically gives him the one power he has truly desired: to become invisible, even if it is for the reasons we like least about his character. This Power Ranger suit, and his ability to use it to become more effective, creates the same dilemma he lived through on Whole Cake Island. Yes, it is a reminder of the lack of humanity of his birth family, but at the same time it is a way to become stronger in order to defeat opponents who could threaten his new family. That is why Sanji does not discard it immediately, despite condemning what Germa does verbally.

It is in the fight against Queen in the middle of Onigashima that Sanji manages to break the barrier of his indecision between the human and the inhuman, and is truly free to make a place for himself among the wings of the Pirate King. In this fight, Queen is a reminder of Judge, being part of the same scientific group as him, and again and again he insists and pressures Sanji to show him the powers of the Raid Suit. Sanji refuses, again and again. But despite his rejection of the suit, his body begins to change, starting by showing the same physical improvements as the brothers he has always criticized: a hard, resistant body and the ability to recover his original form, giving him basically super endurance and resilience. Sanji immediately realizes that becoming an inhuman being is probably not something that is 100% within his control; it may be mere genetics. His desperation and confusion do not allow him to fight with all his strength against Queen, who represents that very influence causing the changes in his body. It even reaches the point where we are shown Queen's representation of what Germa is, giving them the powers of his brothers: he has the electric powers of Niji, he has the laser eyes that Ichiji has, and he has the kind of claw and superstrength that Yonji has, all the superpowers of his brothers.

It is only when Sanji, remembering the influence of his mother and his true nature and responsibility to his captain, who not only saved him multiple times from despair but also gave him a new family that understood and accepted him for who he is, that he manages to make a true decision, a profound decision rooted in the deepest part of his being: to destroy the Raid Suit, the reminder and his bond to Germa, and ironically to accept his inhuman future for the sake of the human he has to be in the present. Sanji decides to use the improvements in his body to create a hotter flame in the form of Ifrit, and even reaches the point of asking his rival Zoro for help so that he can fight with peace of mind, giving Zoro the trust to finish him off if at any moment he loses control. Sanji rejects inhumanity by accepting it, and in that moment he is free and reaches his true level of power, which allows him to defeat someone like Queen.

Sanji's very existence is a contradiction in itself. His birth and evolution owe a great deal to the genetics and inhuman science of Judge and Germa, yet at the same time he is one of the most human and empathetic people in all of One Piece, capable of even accepting the inhumanity he so abhors in order to keep his convictions and be the guardian angel that protects the entire crew. It is something similar to what Zeff did to save him when he was on that deserted island: he demonstrated a complete capacity to give himself up in order to save Sanji, a person he did not even appreciate that much. Sanji seems to be making a similar sacrifice, but with completely different motivations. In this case, what he wants to do is save the crew that has become his new family. A point we cannot forget is that Sanji even reaches the point of asking the last person he would ever want to ask for help, showing a humility that an inhuman being could never possess. And in the end, it all demonstrates that Black Leg Sanji has rejected the inhuman and is the most human of all of One Piece.$grulla$, $grulla$Sanji$grulla$)
) AS v(id, body, title)
WHERE r.id = v.id;
