-- Batch 8: 4 reviews. Run this whole file as one statement.
UPDATE "Review" AS r SET "contentEn" = v.body, "titleEn" = v.title
FROM (VALUES
  ('cmnn873ep000dcndeqf5c483h', $grulla$Zommari:



Ulquiorra:

Ulquiorra Cifer is one of the most iconic, complex, and emotionally impactful characters in Bleach. He holds the number 4 position among the Espada and represents the aspect of death known as "nihilism" or "emptiness." His coldness, his apparent lack of emotion, and his search for meaning within a world he considers empty make him far more than a villain: he is a tragic figure who embodies the absence of hope.
From his very first appearance, Ulquiorra stands out for his distant, analytical behavior. He speaks little, rarely loses his composure, and observes the world and the people in it as if they were phenomena that hold no emotional relevance for him. This way of seeing existence is directly tied to his perception that nothing has meaning and that humans, with their feelings, are weak creatures who seek in emotion what they cannot grasp rationally. For him, the heart does not exist: it is merely a metaphor without substance.
The way he fights is a reflection of his personality: efficient, fast, without excess or emotion. He neither enjoys combat nor prolongs it unnecessarily. If he has to kill, he does so without hesitation. If he can avoid fighting, he will, with complete indifference. He is the perfect executor of Aizen's orders, not out of loyalty born from affection, but because he finds logic in following his will.
In combat, Ulquiorra is incredibly powerful even without releasing his sword. His speed and precision surpass those of most Espada, and his ability to regenerate parts of his body makes him extremely difficult to defeat. He can fire very powerful Ceros from his fingers and from a special organ: the Cero Oscuras, which is far more destructive and characteristic of his higher rank.
But what truly sets him apart is the fact that he possesses a second Resurrección, something unique among the Espada. His first release, Murciélago, already turns him into a darker creature, with great black wings and a gothic, terrifying presence. However, his final form, known as Resurrección Segunda Etapa, transforms him into an almost demonic being, with an aura of total hopelessness. In this form, his power is such that not even Aizen knew Ulquiorra possessed it. It represents the absolute descent into darkness and the complete separation from humanity.
His fight with Ichigo is one of the most intense and emotionally charged in the manga. Ulquiorra represents not only a physical obstacle but a philosophical one: he calls into question everything Ichigo believes about bonds, power, and the will to fight for others. Yet, while he tries to destroy Ichigo, he also begins to undergo an internal transformation. His contact with Orihime and his constant exposure to humanity gradually lead him to start wondering whether that "heart" he so adamantly denies might actually exist.
The emotional climax arrives just before his death. In his final moments, seeing that Ichigo—even transformed into a Hollow—fights to protect others, and as he reaches his hand out toward Orihime, Ulquiorra at last understands the meaning of the heart: not as an organ nor as an empty metaphor, but as an intangible bond between beings. It is in that instant, when for the first time he wishes to touch and be touched, that he disappears.
Ulquiorra Cifer is not simply an antagonist. He is a symbol of what happens when the possibility of feeling is denied, when coldness is embraced as a shield, and when one lives by the conviction that nothing has value. His story is that of someone who believes in nothing, until he dies understanding something he cannot name, but that for the first time he longs to reach.

Harribel

Tier Harribel is one of the most enigmatic and noble Espada in the universe of Bleach. She holds the number 3 position among the Espada and represents the aspect of death known as "sacrifice." Unlike many of her comrades, who act driven by hatred, arrogance, or an obsession with power, Harribel fights for a far deeper reason: the protection of her own.
From her first appearance, Harribel stands out for her serene character, her constant composure, and her silence. She is neither impulsive nor provocative, and she rarely speaks unless it is necessary. But beneath that external coldness lies a very strong sense of loyalty and purpose. Her motivation is not personal power, but the desire to create a less cruel world for Hollows. That is why she leads a group of subordinates—the Tres Bestias—whom she treats with respect and closeness, something uncommon among the Espada.
Unlike others, Harribel does not enjoy combat. She fights neither for pleasure nor for destruction, but because she considers it the only way to protect those who depend on her. Her approach is more defensive and strategic, and although she is perfectly capable of destroying her opponents, she always remains calm, without mockery or sadism. She is a disciplined warrior, but also a maternal figure for the weaker Hollows, which makes her an exception within the brutal hierarchy of Hueco Mundo.
In combat, Harribel is extremely powerful. Her element is water, and she uses her Zanpakutō to manipulate it at will. Even before releasing her sword, she can generate enormous masses of compressed water that cut like blades. This makes her a difficult opponent to predict, since she controls the flow of the battlefield and attacks from a distance.
When she releases her Zanpakutō, Tiburón, Harribel gains partial armor, a large weapon in the shape of a water sword, and a far greater destructive power. Her released form allows her to launch pressurized torrents of water capable of piercing through buildings, create aquatic explosions, and move with great speed. Her mastery of water is symbolic of her character: fluid, adaptable, and powerful, but also contained and not aggressive by nature.
Her main battle takes place against Tōshirō Hitsugaya. The two fight using opposing elements—water and ice—which gives rise to one of the most balanced battles in the series. Harribel never loses control, even when the situation grows difficult. In fact, her defeat does not truly come from being outmatched in combat, but from the betrayal of Aizen, who decides to eliminate her without warning, considering her "unnecessary." This moment makes an injustice clear: Aizen never trusted his subordinates, no matter how loyal or powerful they were.
Harribel survives Aizen's attack, and after the fall of the Espada regime, she assumes leadership of Hueco Mundo as its queen. Her role evolves from warrior to protector, and she fulfills the purpose she always had: to care for the weaker Hollows. Her reign is based on order and stability, not on the imposition of fear.
Tier Harribel is an anomaly in a world of chaos. She represents silent sacrifice, contained strength, and the hope that even among Hollows compassion can exist. She has no need to shout or impose herself with arrogance: her presence alone is enough to inspire respect. Her story is proof that not all monsters are empty inside. Some choose to fight to protect the little they have, even if it means sacrificing themselves in the process.

Neliel

Neliel Tu Odelschwanck, better known as Nel, is one of the most surprising and emotionally endearing characters in the Bleach universe. She was formerly the number 3 Espada, placing her among the most powerful Arrancar, but her story goes far beyond strength. Neliel represents the aspect of death known as "compassion" or "maturity," which sets her radically apart from the rest of the Espada, who are usually dominated by violence, ego, or despair.
When she is first introduced, Nel appears as a childlike creature, clumsy and somewhat silly, with a shrill voice and a playful personality. She travels alongside two companions—Pesche and Dondochakka—and, despite her appearance, shows great empathy and affection toward Ichigo and his friends. This childlike version of Nel conceals her true identity: a former Espada who was betrayed and transformed into her childlike form by an attack from Nnoitra Gilga.
This duality between the tender and the fearsome is one of the elements that makes Neliel so unique. When she temporarily recovers her original form, she reveals a completely different personality: serene, noble, mature, and powerful. She is a skilled and strategic warrior who values justice and fights not for pleasure but out of necessity. During her time as an Espada, she was respected even by those who hated her, precisely because she did not behave like a monster, but like a leader.
In combat, Neliel stands out as much for her brute strength as for her intelligence. She uses a lance as her weapon and possesses great speed, endurance, and analytical capacity. One of her most impressive techniques is the absorption and reversal of the enemy's Cero—the Cero Doble—in which she takes the energy fired at her and returns it with redoubled force. This power represents not only her technical skill but also her philosophy: to take hatred and return it as something more controlled, more precise, more human.
Her confrontation with Nnoitra is one of the most thrilling moments of the Hueco Mundo arc. It is not only a rematch against the one who betrayed her, but also a symbol of the return of her true self. Although she cannot maintain her adult form for long, during the brief time she fights, she proves that her strength never disappeared. What is most striking is not her power, but her dignity: unlike many Espada, Nel does not seek to destroy, but to protect.
Neliel is the exception within the Hollow world. In an environment dominated by the law of the strongest, by resentment and hopelessness, she shines for her compassion, her ability to form bonds, and her integrity. She is not weak for having a heart; she is strong because she has suffered, has been humiliated, and even so retains her essence. Even in her childlike form, that kindness is not lost.
After the fall of Aizen, Nel does not reclaim her position as an Espada nor seek revenge. Her role in the story is more symbolic than military: she is the proof that even in Hueco Mundo, where there seems to be no hope, someone with empathy, tenderness, and the will to protect can be born.
Neliel Tu Odelschwanck is not just a powerful Espada. She is a bridge between two worlds: that of humans and that of Hollows. And in the end, she is living proof that the heart—so debated by Ulquiorra—can exist even in those who were once considered monsters.

Baraggan

Baraggan Louisenbairn is one of the most intimidating, powerful, and symbolic Espada in Bleach. He holds the number 2 position in Aizen's hierarchy, but within himself he still sees himself as the true king of Hueco Mundo. He represents the most inescapable and absolute aspect of death: aging or decay, and his story revolves around his struggle against the inevitability of the passage of time and the loss of power.
Before joining Aizen, Baraggan was the undisputed sovereign of Hueco Mundo. He sat upon a throne of skulls, surrounded by servants who feared and venerated his presence. His power was so great that he could not conceive of the idea that anyone could surpass him. But his reign ended abruptly when Aizen appeared with his Hōgyoku and, with little effort, forced him to submit. From that day on, Baraggan became an Espada, but he never stopped seeing himself as a dethroned monarch who deeply hated the one who had humiliated him.
Baraggan is proud, authoritarian, and absolutely convinced of his supremacy. He has no compassion or respect for anyone, not even for his comrades. He speaks with contempt, acts with coldness, and moves like someone who has no need to hurry because he knows that everything will eventually fall before him. Unlike other Espada who seek to prove themselves, to destroy, or to protect something, Baraggan seeks nothing: he waits for everything that exists to corrupt, age, and disappear. Because he knows that, sooner or later, everything dies.
His power is completely aligned with that vision. Even without releasing his Zanpakutō, Baraggan can slow down time around him, rendering his enemies' movements useless. But his true threat emerges when he releases his weapon and reveals his original form: a skeleton with a royal cloak and a scythe, the perfect symbol of Death itself. His release, Arrogante, grants him the ability to decompose anything he touches—matter, energy, or even time—causing instant aging that consumes everything in its path.
During his battle against Soifon and Hachigen, Baraggan demonstrates why he is considered one of the most invincible Espada. Anything that approaches him rots, collapses, or vanishes. Neither speed techniques, nor kido, nor physical strength seem to affect him. His control over death is absolute. However, that same pride that makes him fearsome also blinds him to his weaknesses. He believes himself to be eternal, and cannot conceive that his power might turn against him.
It is precisely that arrogance that leads to his downfall. Hachigen, with a brilliant strategy, traps part of Baraggan's body together with his own attack—a portion of the aging "Respira"—and forces him to age from the inside out. Baraggan tries to resist, screams, curses Aizen, and casts his final breath in rage toward the sky, like a defeated king who dies cursing the gods.
The fall of Baraggan is not simply the defeat of a powerful enemy. It is a metaphor for absolute power confronted with its ultimate irony: the death he believed he controlled consumes him as well. He is the living representation of the inevitable cycle of decay. His story shows that not even the strongest, nor the most feared, nor even one who believes himself eternal, can escape time.
Baraggan Louisenbairn is the relentless face of slow death. He seeks no glory, no revenge: he simply exists to remind us that everything that begins will eventually end. And when that end arrives, there is no plea, fury, or power that can stop it.

Starrk

Coyote Starrk is the number 1 Espada in Aizen's army and represents the aspect of death known as loneliness. Despite being at the summit of power among the Arrancar, Starrk is the complete opposite of what one would expect from an elite warrior: he is calm, indifferent, lazy, and, above all, profoundly melancholic. His story is the quietest and the saddest among the Espada, because his power does not come from a desire to dominate, but from a desire not to be alone.
From his first appearance, Starrk shows himself as someone listless, who sleeps in the middle of meetings and avoids actively taking part in conflicts. He does this not out of arrogance, but from a lack of motivation. He is a character who seeks neither fights nor glory. He is there because he has nowhere else to go. He is accompanied by Lilynette Gingerbuck, a loud and energetic companion who is actually part of his own being—a division of his soul—which already hints at how isolated he is, even within himself.
Starrk's story reveals that, when he was a Hollow in his most primitive state, his spiritual energy was so high that simply by being near him, other Hollows died. He was incapable of having company because his power destroyed everything that tried to approach him. It was then that his soul, in an unconscious attempt to stop being alone, split in two: him and Lilynette. That division saved him emotionally, but it did not cure his loneliness.
Starrk did not join Aizen out of ambition, but because, for the first time, he found a group he could belong to without killing anyone simply by existing. For him, the Espada—despite their differences—represented a kind of refuge, a place where he was not a solitary monster but part of something. His loyalty to Aizen is not devotion, but gratitude. He follows him neither out of fear nor ideology, but because being alone again is more unbearable to him than obeying orders.
In combat, Starrk is as lethal as he is serene. He is a master of Sonido, extremely fast, and possesses great endurance. He can fire multiple Ceros simultaneously, summon a rain of spiritual energy through his pistols in his released form, and fight both at a distance and in close combat with absolute efficiency. His Zanpakutō, Los Lobos, transforms him into a gunman accompanied by wolves of spiritual energy that explode on contact. His fighting style reflects his personality: not aggressive, but unstoppable when forced to act.
His confrontation against Shunsui Kyōraku is one of the most elegant and meaningful of the Karakura arc. Both are relaxed men, reluctant to fight unnecessarily, but extremely dangerous when they do so in earnest. The battle unfolds like a game of mutual respect, where subtle strategies and personal principles weigh more than the simple desire to win. In the end, Starrk is defeated by Shunsui's cunning, but he never loses his dignity.
Starrk's death is silent, without screams or vengeance. He dies looking up at the sky, remembering Lilynette and wondering whether having tried to seek company was enough. His end is as solitary as his existence, but also deeply human. He did not fall out of weakness, but because he could not help being who he was: a soul broken by isolation.
Coyote Starrk is the embodiment of the warrior who never wanted to fight, of the being who had everything except the one thing he needed: someone to share his existence with. His power was not a blessing, but a barrier that separated him from others. And in that emptiness, in that quiet sadness, is where his true tragedy lies.$grulla$, $grulla$Espada Part 2$grulla$),
  ('cmnn8735l000bcndecqpj8djm', $grulla$The cursed spirits from Geto's, or Kenjaku's, group in Jujutsu Kaisen are easily some of the characters with the most prominence in the entire series, showing and explaining to us everything from their conception to their development, as well as a large part of the range of abilities available to special grade cursed spirits like them. However, only one of them has shown us two stages in the development of cursed spirits, and in my opinion, that makes him fulfill a rather particular role in the story. Of course, I'm talking about our favorite creature from the depths, Dagon.

When we first see him, it's easy to notice the contrast between Dagon and the rest of his companions, since the intimidating curses like Jogo, Mahito, and Hanami give us the impression of developed cursed spirits, and almost from the very start they show us their power levels. Dagon, however, is a small exception, since his physical form is rather cute and not very intimidating, and on top of that he doesn't participate in combat in this form. Of course, later on we realize that Dagon's chubby little octopus form is actually his stage as a cursed womb, a kind of metamorphosis stage in which he has not yet acquired all his special grade powers, though he is clearly not defenseless, being able to devour hundreds of humans with his torrents of water. Given his small form, it's easy to overlook Dagon, but keep in mind that this curse was born from humanity's fear of aquatic natural disasters, making him in theory as powerful as Jogo, as well as being a sort of counterpart to him. The reason we consider Jogo to be much stronger than Dagon is that the latter has not had time to develop and learn how to use his abilities.

It's not until his fight against Nanami, Maki, and Naobito that Dagon is forced to evolve and leave behind his cursed womb form, becoming a full special grade cursed spirit. With this, his form changes radically, reminding us more of a Lovecraftian Cthulhu than a cute red octopus. His power level immediately skyrockets as well, far surpassing first grade sorcerers.

Another aspect that changes radically with his transformation is his personality. In his cursed womb form, Dagon is shy, quiet, and sensitive, crying when he feels threatened. But in his final form, Dagon is imposing and intimidating, demonstrating a great love for his fellow natural disaster curses, as well as a strong desire for revenge and self-preservation.

In terms of power level, Dagon is a special grade curse with the dangerous ability to generate and control water. This makes him a great threat, close to the level of his allies, despite his lack of hostility while he existed as a cursed womb. Even when he was docile, Dagon could easily dispose of dozens of weak non-sorcerers by devouring them all at once with the water. However, in this basic form he was vulnerable when alone and could not stand up to strong sorcerers like Naobito.

Of course, Dagon is much more powerful in his evolved state, in part due to his increased intelligence and his physically imposing form. In this form, he can generate water on such a scale that Maki claimed it far surpassed the Maximum Elephant. Neither Naobito nor Nanami, working together, could exorcise Dagon as quickly as one would expect from two grade 1 sorcerers. Naobito, head of the Zenin clan at the time, recognized that Dagon had raised his cursed energy to immense levels and had access to a wide range of techniques. Dagon's jujutsu was only outmatched by Naobito's speed until the cursed spirit created an opportunity to unleash his Domain Expansion.

Dagon's general intelligence matured exponentially when he evolved. When his cursed technique was outpaced by the speed of his adversaries, Dagon fled upward to evade them. He recognized that he could not directly outpace Naobito's speed, so he distracted him with a technique-activation gesture, giving himself just enough of an opening to launch his domain. But let's not get ahead of ourselves; let's first talk about his cursed technique.

Innate Cursed Technique: Disaster Tide

This technique allows the user to manifest large volumes of water and control it using their cursed energy. It is incredibly versatile, allowing for use at all ranges. It can be used as a water shield for close and mid-range combat, and as a large sweeping wave for long-range combat.

Its efficiency depends on the user's cursed energy, and as such it can only be used to its full potential by someone skilled in the use of cursed energy like Dagon. If used to its full potential, this cursed technique can produce water that far surpasses that of the Maximum Elephant. The waves can be used as concussive force or simply to overwhelm opponents by mass and speed.

The crowd-control ability of Dagon's technique makes it valuable especially when he fights alongside his allies, but even when he is alone he has proven to be extremely effective in battle, though perhaps not as much as the rest of his allies.

Dagon's true threat comes when he activates his domain expansion: Horizon of the Captivating Skanda

Dagon's Domain Expansion is conjured when Dagon forms a seal over his stomach. This creates a tropical beach that has a forest of palm trees on one side of the coast and an ocean on the other side, stretching toward the horizon. It has been described as a tranquil domain, and its waters are shallow enough that someone can stand in them near the beach.

The Horizon of the Captivating Skanda has a sure-hit technique that allows the shikigami Dagon creates to automatically strike their target. From the target's point of view, the fish appear suddenly, which makes them nearly impossible to block since the shikigami do not exist until they hit the target, instantly devouring their flesh.

Within his domain, Dagon can use an additional technique, called the Death Swarm

The activation of the Death Swarm summons countless species of marine shikigami that represent the constant source of life in the sea. The man-eating shikigami attack in an endless torrent of shikigami that will keep overwhelming the target and devouring them for as long as the domain's guaranteed-hit function is active.

Dagon precisely assigned specific percentages of his domain's abilities to his targets and nearly wiped out all of his opponents. He was able to overcome Naobito's Falling Blossom Emotion defense by using the endless swarm of shikigami to block his sight before attacking. Once Dagon's infallible attack was neutralized by Megumi, he quickly changed strategy and focused on eliminating the competing domain. Although Dagon initially misunderstood Megumi's intention, he eventually understood that Megumi planned to use his domain to create a hole through which everyone could escape.

It's clear that under normal conditions Dagon would have been able to beat Naobito, Maki, Nanami, and Megumi even working together; it was only Toji's intervention that spelled bad luck for our favorite aberration of the depths, and caused his death given the overwhelming strength of the reincarnated Zenin.

Despite only having one important fight in the entire series and spending most of it in a cursed womb form without much thematic usefulness, Dagon's sudden evolution gives us a greater understanding not only of the emotions of special grade cursed spirits but of how they can come to evolve to that level of power. Additionally, the inspiration behind his physical form and his powers makes him someone quite interesting, and worthy of having prominence in the few chapters in which he had it.$grulla$, $grulla$Dagon$grulla$),
  ('cmnn872ij0007cndenjlmda93', $grulla$There are antagonists who, if you give the story a little twist, become the protagonists. People whose methods or motivations may seem twisted or evil, but who, once you understand their perspective, you start to see in another light, and you may even grow fond of them or identify with them. Hunter X Hunter has shown us several examples of this type of character, and in my opinion some of its best executions, with Chrollo Lucilfer, the leader of the Phantom Troupe and Kurapika's archenemy, being the clearest of them all.

Chrollo is calm, intelligent and charismatic, since he seems to be a born leader, capable of keeping the Troupe together despite the volatile personalities of its members. Although he is a highly capable strategist, Chrollo also has great confidence in his own fighting abilities, as well as in those of the other members of the Spiders. He always has at least two people with him, which is why Hisoka found it so difficult to fight him. After admiring the objects he has targeted and acquired, Chrollo sells them all. It is also said that Chrollo likes old books.

Unshakable and unflappable, he is also an observer of human nature. Gon's hostility toward the Troupe led Chrollo to reflect on the nature of himself and his actions. Furthermore, while fighting Hisoka, who refused to back down even after seeing the magnitude of his abilities, Chrollo expressed a fascination with the inner workings of human beings. However, by his own admission, he sees no difference between a puppet and a person.

Chrollo shows no fear of his own death; he even anticipates it. Melody stated that his heartbeat sounded as if he were happy living alongside death. For Chrollo, the Troupe is more important than his own life. He once stated that the survival of the group takes precedence over the well-being of the leader, emphasizing that the head of the Spiders is just another member who can be sacrificed for the survival of the whole. To prevent his misfortunes from coming true, Chrollo ordered the members of the Troupe to stay close and help one another. The only people Chrollo seems to care about are his fellow Troupe members. When he reads his fortune, written by Neon, which alludes to Uvogin's death, he weeps for him. Later, he organizes a massacre of Mafia members as a requiem for his fallen comrade. After the deaths of Kortopi and Shalnark at Hisoka's hands, Chrollo appears visibly distressed and furious, swearing to kill him as soon as he sees him.

Like the other members of the Troupe, Chrollo is ruthless, relentless and not above committing inhuman mass murders, most notably when they brutally slaughtered the Kurta Clan. Furthermore, his use of Indoor Fish on an assassin reflects his apathetic nature toward his enemies. The atrocious murder of his dear friend Sarasa and his thirst for revenge against the perpetrators have desensitized him to such atrocities. A hostility between Chrollo and Silva Zoldyck is also suggested, probably stemming from their earlier encounter after Silva killed a member of the Troupe.

Chrollo is a skilled and quite manipulative actor, as shown when he met Neon Nostrade and "befriended" her in order to steal her fortune-telling ability. During that time, he presented himself as a kind and helpful man, always enthusiastic and smiling, who also showed curiosity. However, Chrollo only intended to learn about Neon's ability in order to fulfill one of the conditions necessary to steal it. While kidnapped, Chrollo also proved to be quite provocative and sinister toward Kurapika.

It is said that the inhabitants of Meteor City also share notable bonds that have been described as "thinner than water, and yet thicker than blood." This was also demonstrated by the fact that the Phantom Troupe is an important asset in the city's defense.

Chrollo is shown to have been emotional, affectionate and bright as a child. He also always brought fresh flowers for the graves of the children at the church. Father Lisores remarks to an elder of Meteor City that he sees great potential in Chrollo due to his spirit and original ideas.

In terms of power level, as the leader of the Phantom Troupe, Chrollo is an exceptional fighter and is revered as the strongest by most of its members. Machi clearly ranks him above Hisoka, who has consistently wished to fight the Troupe's leader far more than any other Spider. However, Chrollo tends to hold back if his opponent possesses an ability that interests him so that he can steal it. He was able to fight Silva and Zeno Zoldyck simultaneously, both extremely competent assassins, without leaving any opening for the former to exploit, although he was unable to cause them significant damage and was ultimately saved by Illumi fulfilling his contract. In the past, he survived a confrontation with Silva, and Zeno stated that he would surely win if Chrollo fought to steal his ability, but that his victory would be less certain if Chrollo were serious about killing him. His greatest achievement on the battlefield may be his victory at Heavens Arena against Hisoka, another extremely powerful Nen user who at the time had no record of past defeats or even any evidence of having struggled in fights.

Chrollo's fighting style is adaptable and combines speed with deadly precision. He is capable of killing skilled assassins with just a pen, sometimes even remaining hidden with Zetsu, without using Nen at all as a result. Chrollo also possesses extraordinary strategic skills, as well as astonishing mental strength and willpower, even by the Troupe's standards.

Chrollo is in possession of one of the famous Ben's Knives, forged in the central period of Delon. It has a black handle with a slightly curved guard, similar to a D-guard. Near the guard, the blade splits into two segments. The central one is the longest and ends in a sharp, arrow-shaped point. The second segment is curved and serves as the knife's edge, with its tip almost touching one of the central segments. A third segment acts as the back of the blade, connected to the others through two horizontal bars. Ben's Knives are known for their exceptional sharpness, which allowed Chrollo to cut Silva's skin, a feat that led the assassin to recognize the quality of the weapon. Silva also deduced from the shape of the blade that it was poisonous. The poison was so potent that 0.1 mg could paralyze a whale. Chrollo kept it hidden in a curved sheath under his clothes.

As far as his Nen is concerned, Chrollo is a Specialist. His talent for Nen is considered prodigious not only for his age, but even by the standards of masters of the discipline. Silva pointed out that his Zetsu is impeccable, allowing him to sneak up on his opponent and kill them without leaving the slightest trace of bloodlust, although Hisoka was able to detect him in an instant on at least one occasion. Like other skilled Nen users, he is able to maintain a state of Ten at all times. His prolonged use of Ren in confrontations suggests that he can also use Ken. In addition, he has knowledge of Gyo. However, the technique he relies on most appears to be Hatsu, proving to be extremely versatile in his use of it. He has been able to employ numerous stolen abilities in battle with great effectiveness, despite the fact that they use different types of Nen, and he has even used multiple Nen abilities simultaneously, thus demonstrating his vast reserve of aura. It is currently unknown whether this is entirely due to his own abilities or whether Skill Hunter allows him to mimic the skill of the ability's original owner.

Although Chrollo ranked seventh in the Troupe in arm wrestling, this is impressive considering that Specialists are the weakest in the use of Enhancement abilities. Moreover, his defensive use of aura is so great that, despite fighting Silva and Zeno at the same time and withstanding powerful blows, he only suffered relatively minor damage that did not affect his combat abilities, although he immediately understood that he would not be able to defend himself against Zeno's superior Gyo and collapsed from exhaustion right after the fight.

Because of Kurapika's Chain Jail, he was left unable to use Nen for a time. After the exorcism was performed, he acquired new abilities for the purpose of fighting Hisoka. The creation of Double Face and his explanation of The Sun and Moon imply that he knows about legal loopholes and post-mortem Nen, respectively.

Let's talk a little about Chrollo's Hatsu, Skill Hunter, or Bandit's Secret

Chrollo can steal the Nen abilities of others to use as his own through a conjured book known as "Bandit's Secret." The victim, of course, no longer has access to the stolen ability. The theft occurs under strict conditions:

Chrollo must witness the Nen ability in action with his own eyes.
He must ask questions about the Nen and be answered by the victim.
The victim's palm must touch the handprint on the cover of Bandit's Secret.
All of the above must be completed within one hour.
To use a stolen ability, Chrollo first conjures Bandit's Secret and turns to the page of the desired ability. The book must remain open in his right hand, which allows him to use only one ability at a time. Abilities are subject not only to the limitations but also to the emotions and thoughts of their creators. For example, despite seeing corpses as motionless masses no different from objects, Chrollo cannot use Order Stamp on them due to the original owner's opinion. Furthermore, an ability disappears from the book if its former owner dies. However, if post-mortem Nen is involved, Chrollo can still use the ability. Expert Nen users can understand some of these conditions, like Zeno, who correctly guessed that Chrollo needed to fulfill four or five of them before being able to steal an ability.

Additionally, Chrollo can use Double Face, which allows him to maintain access to any of his stolen abilities on the page of his book. Even if the book is closed and he is not touching it, acting as an exception to one of the conditions of his main ability. With both hands free, Chrollo can fight hand to hand in conjunction with his stolen abilities. Furthermore, if Chrollo keeps the book open to a particular page and uses his bookmark on another page, he can use two stolen abilities at the same time. This bookmark seems to belong to the book itself, and not to be a stolen ability.

The ones that are stolen abilities are the following:

Indoor Fish:

These Nen Beasts, described as a fish that can only survive in a completely sealed room, appear to be made entirely of bones and feed on human flesh. While a person is being devoured, they feel no pain and do not bleed, and will remain alive and perfectly conscious even if mortally wounded. When the fish disappears, the effects of the wounds manifest, most likely resulting in the victim's death. Chrollo summoned two of them when fighting an assassin hired by the Ten Dons.

Fun Fun Cloth

An ability originally belonging to Owl, a member of the Shadow Beasts. The cloth is conjured and can increase and decrease in size according to the user's will. Anything covered with the cloth, even an object as large as a car, decreases in size until it fits in the palm of the hand. The user can then return it to its original size by taking it out of the bag. People can also be shrunk in this way, without suffering harm. After Owl used it to move the objects at the Underground Auction, he was eventually captured and tortured by the Troupe, during which Chrollo stole the ability. Chrollo then used this ability in his fight against Silva and Zeno, attempting to capture the latter so that he could steal his ability as well.

Teleportation:

Chrollo showed the ability to teleport a person from one place to another without that person's consent. He did so by remaining motionless and without seeing the person he wanted to teleport or the destination. He used this ability on Nobunaga to prevent him from attacking Hisoka. Both Phinks and Machi were unaware that Chrollo possessed this ability.

The Sun and Moon:


Two symbols appear on the backs of Chrollo's hands: a sun with a plus sign on his left hand and a waxing/waning crescent moon with a minus sign on his right hand. By touching the desired target, he can mark them with a different symbol depending on which hand he used. When the two symbols touch each other, they cause an explosion. The symbols can be created instantly, but to reach their maximum power, Chrollo needs to touch the target for three to five seconds. In the latter case, the explosion is powerful enough to kill the people around the bearer of the symbols, not just the bearer themselves. A symbol can be fully charged even after its application, through physical contact. Despite Chrollo claiming that the symbols themselves explode, fully charged symbols were able to turn whatever they were applied to into a bomb, even parts separated after the symbols were applied. The ability was stolen from the elder of Meteor City. Although he has since died, his Nen became so powerful after his death that Chrollo was able to retain his ability. For the same reason, once the symbols are applied, they will remain until they explode, even if Chrollo's book is closed. Their power is such that they can counteract Skill Hunter's restrictions, preventing a copy created with Gallery Fake from disappearing even after the ability is no longer in use, if a symbol has been applied to it. The Nen type of this ability is currently unknown, although its effects could be explained by a combination of Emission and Transmutation.

Order Stamp:

Chrollo conjures a stamp that, when applied to a "puppet," allows the user to control it after giving a vocal command. To be considered a puppet, the object the user wishes to control must have a head and be lifeless. This ability cannot be used to control corpses, since the original user did not see them as mere inanimate objects; however, it can control Nen copies of corpses. Removing the puppet's head will deactivate the ability. The stamp bears the kanji for "person" (人) and leaves the same mark when applied. The ability is capable of controlling a large number of puppets, but the orders cannot be too complex. Chrollo discovered that if he controls the copy of a person, giving orders that go against that person's beliefs can be detrimental, so much so that sometimes the order is ignored. However, he discovered that using language that creates emotional distance, such as saying "break" instead of "kill," can bypass the puppet's will. This is one of the abilities Chrollo stole to fight Hisoka, and it can be used to control more than 200 puppets at the same time.

Convert Hands

Two marks appear on the palms of Chrollo's hands: a black arrow pointing upward inside an empty circle on his right hand and a white arrow pointing downward inside a filled circle on his left hand. By touching a target with his right hand, it takes on Chrollo's appearance, while by touching it with his left hand, Chrollo takes on the target's appearance. If Chrollo touches a target with both hands, both instantly change form. The ability only affects appearances, not abilities or personalities. Since the marks remain on Chrollo's hands, it is relatively easy to identify him, although clothing can be used to conceal them. Nonetheless, it is an effective way to blend into a crowd. For the mark to appear on his right hand, which would otherwise hold the book, Chrollo needs to use the bookmark, but after activating the ability, he can hold the book normally. This is one of the abilities Chrollo stole to fight Hisoka. It is currently unknown what type of Nen it uses. Its characteristic of making the affected object indistinguishable from the original makes it vaguely similar to some Conjuration abilities.

Additionally, Chrollo has stolen abilities that he no longer possesses within his arsenal, such as Neon's Lovely Ghostwriter, Kortopi's Gallery Fake, or Shalnark's Black Voice. It seems that Chrollo can return the abilities he steals, or that they disappear upon the death of the original user and vanish from his book.

Chrollo is an interesting character. On the one hand, we know he is a psychopath who would do anything to protect or avenge his own, yet isn't this what the other protagonists of Hunter x Hunter do as well? It's just that Chrollo is a bit more brutal and realistic about it. Additionally, his abilities demonstrate the versatility of Nen, and thanks to him we learn more about many other Nen techniques in greater detail, which makes him deserving of his popularity.$grulla$, $grulla$Chrollo Lucilfer$grulla$),
  ('cmnn8729c0005cnde8333utlz', $grulla$Not every series makes the most of its secondary characters. Most simply introduce them and then, especially if they're antagonists, discard them without a second thought once they've been defeated. However, one area where Dandadan stands out is in the use and development of its minor antagonists, giving them backstories, motivations, and even future roles that are quite interesting, and there's no better example of this than Peeny Weeny, better known as Mr. Mantis Shrimp.

Surely many of you recognize this muscular fellow with boxing gloves from the Serpo mini-arc as the contractor brought in by the Serpo aliens to finally kidnap Momo and Okarun and steal their banana organs. Yet, despite being an extremely secondary character, the series takes the time not only to show us his combat abilities, but also his motivations and even possible future roles.

The first thing that's obvious from his name is that Mr. Mantis Shrimp is an alien based on... mantis shrimp, a real animal known for the supersonic strike it uses to defend itself from predators and even to hunt its prey. His original form actually doesn't resemble the animal all that much, being a yellow humanoid with a tie, black shorts, and boxing gloves, plus a disc on his head from which his eyes protrude. However, the form modified by the Serpo aliens resembles the animal far more closely, from the particular shape of its supersonic claws to its eyes and coloring.

In terms of his personality, Mr. Mantis Shrimp is a fairly complex individual. When we first see him, he's an aggressive but talkative fighter, who tends to sing or boast about his enhanced strength, or trade words with his opponents. Notably, he's very deferential toward the Serpos, who were his employers, frequently apologizing for his less-than-desirable performance.

Largely as a result of being a weak fighter by his species' standards, Peeny-Weeny, as he's really called, has led a life full of hardship. His wife passed away from a congenital illness, which his son, Chiquitita, also inherited. Because Chiquitita needs regular blood transfusions due to his illness, Mr. Mantis Shrimp takes on dangerous jobs to pay for them. His relative weakness earned him the scorn of his people and the mockery of his employers, which affects him deeply. Therefore, when Momo, Seiko, and company tended to his wounds, provided him with a meal to aid his recovery, and offered a cow for his son's blood transfusions, Mr. Mantis Shrimp was overcome with emotion and vowed to help them in any way he could, showing his gratitude and nobility.

Although he's willing to take part in fights for a just cause, Mr. Mantis Shrimp claims to be a pacifist and refused to teach Okarun how to throw a good punch because he believes violence is wrong. However, he admits that he's prone to lashing out if his patience is tested, such as when he's behind the wheel and his passengers complain about his poor driving skills.

It goes without saying that Mr. Mantis Shrimp's main ability is his incredible physical strength, combined with his boxing technique. He's capable of throwing punches so powerful they can break walls, despite being considered a relatively weak specimen of his species.

His main technique is the Jet Punch, with which he puts all of his strength into a single punch that sends his opponent flying. Although Aira was able to dodge this attack, it's no exaggeration to say it can break bones and do considerable damage if it connects, in addition to being extremely fast.

Mr. Mantis Shrimp is capable of taking on his race's powered-up transformation, called Strong Style 24. In this form, his head resembles that of a mantis shrimp, with bright green eyes. A second pair of large eyes, along with extended antennae, forms the top of his head, which blinks in response to his speech. Around his neck he has a segmented, collar-like structure. His hands transform into the raptorial appendages of a mantis shrimp, with concentric rings of green, red, and orange that can open up and act as shields. His feet are wide and flat, resembling fins or the feet of an aquatic creature.

Ironically, despite the change in appearance that makes him resemble the crustacean, along with a more effective boost in strength in aquatic environments, this form does not grant Mr. Mantis Shrimp gills to breathe underwater. As a result, he must surface occasionally to avoid drowning. He's also limited to remaining in this form for 24 seconds; however, with a special drug, such as a Serpo Energy Drink, his time can be extended to at least 24 hours.

The enhanced physical strength Mr. Mantis Shrimp gains in this form increases his striking power and speed to the point of generating shockwaves with every punch. In addition to allowing him to fight at a distance, these shockwaves prove too difficult for his opponents to dodge, unless they possess extraordinary speed and reflexes.

In keeping with his resemblance to the mantis shrimp, the enhanced strength provided by the form increases significantly when Mr. Mantis Shrimp is submerged underwater. According to him, his strength multiplies tenfold under these conditions.

Also in this form, his Jet Punch changes into an enhanced version when underwater. This version is extremely powerful, capable of destroying high-level armor as well as finishing off both humans and aliens in a single blow.

Lastly, there's the Salaryman Uppercut, a blow that sends his opponent flying upward extremely fast, pinning them to the ceiling, as we can see with poor Aira.

The great thing about Mr. Mantis Shrimp is that he isn't used as an invincible enemy, or even as a wall that teaches the group of protagonists a great deal. His purpose is more to expand the world of the aliens, showing us that there are hierarchies and mundane motivations for the different species, as well as familial love within them, and not just the cold motivations of the Serpo. In fact, his existence makes us wonder what other kinds of aliens might exist in the cosmos, and how they might help or threaten humanity and the Yokai of Earth. Furthermore, Mr. Mantis Shrimp's ability to adapt to a normal job on Earth, and his ability to cooperate with Momo and company, are the first sign of the series introducing aliens as key pieces on humanity's side in its war against being conquered or annihilated, making him, despite being a minor character, someone who actually offers quite important narrative hints in the series.

This great family man with established, strict values and a fairly powerful left hook is actually one of my favorite characters, despite being one who doesn't have much screen time, and I can't wait to see the rest of his exploits adapted into this great anime.$grulla$, $grulla$Mantis Shrimp$grulla$)
) AS v(id, body, title)
WHERE r.id = v.id;
